src/store/modules/wallet.js
Occasionally, we would see a transaction fail to relay because the
fee per byte was too low. This was because we were not considering
the size of the final change output in our calculations for generating
extra stamp-sized UTXO outputs
This commit updates the calculates to ensure that extra UTXO is
considered when calculating how many excess UTXOs to create.
=> Fix generation of change outputs so that fees are correct

src/store/modules/chats.js
Due to using the payload hash from the server, it was in a different
format than we were using to store the message keys. This commit
fixes that, so we re-compute the hash and check it. This is required
for security purposes anyways.
=> Ensure messages aren't displayed twice

test/jest/__tests__/crypto.test.js
=> Fix crypto encrypt/decrypt test that broke due to API change

package.json
Add a "yarn build" script so you don't need to install quasar globally.
=> chores - add build script

src/store/modules/wallet.js
Previously we were storing privKeys and addresses in a different
format. They did not need special consideration when rehydrating.
However, they are now rich objects and require reinstantiation. This
commit adds that to the rehydration code.
=> Fix rehydration of UTXOs

src/components/MainHeader.vue, src/components/Settings.vue
As per title. Delete some unused widgets that were confusing testers.
We can add these back later was we add actual functionality. What we
have right now seems to be good.
=> Clean up unused widgets for the time being

src/store/modules/wallet.js
Currently, the wallet generates a number of fixed size change outputs,
and uses the bitcore transaction library to generate the change output.
However, wallets on Stamp should not use a single change output, and
should strive to have a number of outputs of various sizes available.
This commit adjust the change output creation to decrease by ~2x for
each change output down to the dust limit. Any remainder is then
randomly distributed among the existing UTXOs.
This should enable the ability to often have transactions *without* any
change output as the disitrbution of UTXOs better follows a
power distribution.
Later commits should seek to minimize which txns the outputs come from.
=> Improve wallet change handling

package.json, yarn.lock
As per title. This is significantly easier to use than the native
date object.
=> Add moment library for date manipulation

src/pages/Chat.vue
Make scrolling a bit cleaner and faster
=> Minor updates to scroll related code in Chat component

src/pages/Chat.vue, src/store/index.js, src/store/modules/chats.js
This commit removes the active chat input from the vuex store in
favor of saving it on hidden component state.
=> Remove active chat input from store in favor of component state

src/store/modules/chats.js
By freezing these message objects, we avoid it becoming observable. This
is fine because these values should not change, and this saves quite a
few resources.
=> Freeze our immutable message values

src/store/modules/chats.js
It turned out to be quite expensive to re-calculate contact "values"
each time we wanted to store. This commit addresses that by creating
pressive aggregates. This also allows them to be observable as well.
=> Progressively compute and store contact's total value for sorting

src/components/chat/ChatListItem.vue, src/components/drawers/MyDrawer.vue, src/store/modules/chats.js, src/store/modules/contacts.js
This commit removes excess code as per title.
=> Remove openChat function which duplicates setActiveChat

src/store/modules/chats.js, src/store/modules/contacts.js
Update contact profile as soon as the user is selected so that
updates to relay address, among other things, are updated immediately.
=> Update contact profile when selected

src/layouts/MainLayout.vue
This commit only shows the main chat areas after the state has been
fully updated. This ensures that the DOM isn't re-updated for each
message we load. Additionally, it parallelizes the updating of the
HD wallet/fixing UTXOs and downloading new messages -- as these
processes are largely independent.
This decreases load/import times significantly.
=> Improve load times significantly

src/store/modules/chats.js
We incorrectly were setting the wrong key for `messages` during a
previous refactor. Additionally, the contact wasn't being created when
trying to "send local" for the first time to a new person. These two
issues made it so you could not talk to new people. This commit address-
es both of those issues by fixing the key and adding a check to create
the contact. It also adds a migration to fix the data store of people
who downloaded the last release.
=> Fix bug with adding a new contact

src/components/drawers/DrawerContactCard.vue
Improve the look, just a tiny bit.
=> Remove ugly material background that hits 3rd party service

src/pop/index.js, src/relay/constructors.js, src/store/modules/wallet.js
As this wallet isn't a general purpose wallet, this commit moves the
fee logic entirely to the wallet.
=> Keep fee logic internal to the wallet.

src/components/dialogs/SendFileDialog.vue
Remove some refernces to the wallet from the send file dialog that
were not being used.
=> Remove dead code from send file dialog

src/relay/client.js
This commit adds a self-contained relay client that does not depend
on Vuex for it's internal workings. It accepts a small adapter that
allows the integration of various stores and other reactivity systems.
=> Add self-contained relay client that does not depend on Vuex

src/boot/setup-apis.js, src/components/MainHeader.vue, src/components/chat/ChatList.vue, src/components/context_menus/ChatMessageMenu.vue, src/components/dialogs/NewContactDialog.vue, src/components/dialogs/ProfileDialog.vue, src/components/dialogs/RelayConnectDialog.vue, src/components/dialogs/SendBitcoinDialog.vue, src/components/dialogs/SendFileDialog.vue, src/layouts/MainLayout.vue, src/pages/Chat.vue, src/pages/Setup.vue, src/store/modules/chats.js, src/store/modules/contacts.js, src/store/modules/keyserver_handler.js, src/store/modules/relay_client.js, src/utils/relay-client-factory.js, src/wallet/index.js
This commit integrates the factored-out relay client into the rest of
the codebase and Vuex store for state. The goal here is to create self-
contained libraries which could be used to build bots and other items
things in the future. Additionally, these components will be able to be
tested in the future more easily, and more clear what state they
depend on when refactoring.
=> Integrate new relay client with the rest of the codebase

src/components/drawers/ContactDrawer.vue, src/store/modules/chats.js, src/store/modules/contacts.js
There are a few pieces of dead code in the store. This commit removes
a substantial portion of them.
=> Remove excess store functions

src/store/modules/chats.js
This is garbage leftover from previous refactors, and missed.
=> Remove leftover function in chats store

src/components/context_menus/ChatMessageMenu.vue, src/components/dialogs/SendAddressDialog.vue, src/pop/index.js, src/relay/client.js, src/relay/constructors.js
This commit is a major refactor of the message construction APIs that
deduplicates a lot of code for generating payloads and sending messages.
This was motivated by the need to refactor a significant number of
different locations in the code when updating logic for sending
messages to deal with edge cases. As such, there is now one place that
generates and sends message payloads.
=> Major refactor of message construction APIs

src/pages/Chat.vue, src/relay/constructors.js
Fixes to `setReply` and `constructReplyEntry` functions.
- `setReply` simplified for local state
- Fix type errors
=> Fix replies

src-electron/main-process/electron-main.js
=> Prevent re-opening second app instance

src/wallet/index.js
This commit makes the format of UTXOs the same for every keytype. This
makes it easier overall to work with UTXOs without guessing where the
privkey is stored, and how to fetch it.
=> Remove most of the specialization around hd wallet utxos

src/relay/client.js, src/wallet/helpers.js
This commit makes the internal message API consistent with the wallet
utxo schema. This is purely core consistency.
=> Refactor output value calculation

package.json, src/components/chat/ChatInput.vue, src/components/dialogs/WalletDialog.vue, src/components/setup/ChooseRelayStep.vue, src/components/setup/DepositStep.vue, src/components/setup/IntroductionStep.vue, src/components/setup/ProfileStep.vue, src/components/setup/SeedStep.vue, src/components/setup/SettingsStep.vue, src/layouts/MainLayout.vue, src/pages/Setup.vue, src/utils/constants.js, yarn.lock
**Motivation**
A fair few people have expressed concern around the setup procedure - specifically they feel lost and misunderstand the steps required to get going.
**Fix**
This includes explanations as they progress through the stepper, among other UI improvements.
=> Improvements to the Setup stepper

src/components/chat/ChatList.vue, src/components/dialogs/WalletDialog.vue, src/components/setup/DepositStep.vue, src/utils/formatting.js, src/wallet/index.js
Simple refactor of utilities module - changing `export default` to individual `export const` functions.
=> Switch utilities from export default to individual exports

src/components/setup/SeedStep.vue
=> Add .trim() to imported seed

src/pages/Chat.vue
=> Fix sizing issues

src/components/chat/ChatInput.vue, src/pages/Chat.vue
=> Improve msg box focusing

src/components/drawers/DrawerContactCard.vue, src/css/quasar.variables.sass
=> change quasar colors, update contact card to use secondary color

src/layouts/MainLayout.vue
As per title.  Very minor styling change
=> Ensure all components have proper borders

src/pages/Chat.vue
As per title. Looks good there.
=> Add contact avatar to chat-area header

src/components/dialogs/NewContactDialog.vue
Thank you for contributing to Stamp! We really appreciate it. Our mission is to spread P2P electronic cash to the world.
=> Trim address entry for new contact dialog

src/components/chat/ChatMessage.vue, src/components/chat/ChatMessageSection.vue, src/pages/Chat.vue
This commit futher diverges from the default quasar `q-chat-message`
component in favor of something we can customize more. The current
version of this is very dry, but serves the purpose. We will be
able to easily iterate on the design in the future.
=> Create a custom chat-message component

src/relay/client.js, src/utils/image.js
Basic refactor of the image utils module
=> Refactor image utils

babel.config.js, src-electron/main-process/electron-main.dev.js, src-electron/main-process/electron-main.js, src/components/chat/ChatListItem.vue, src/components/chat/ChatMessage.vue, src/components/context_menus/ChatMessageMenu.vue, src/components/dialogs/NewContactDialog.vue, src/components/dialogs/ProfileDialog.vue, src/components/dialogs/SendAddressDialog.vue, src/components/dialogs/WalletDialog.vue, src/components/setup/DepositStep.vue, src/keyserver/handler.js, src/pages/Setup.vue, src/pop/index.js, src/relay/client.js, src/relay/constructors.js, src/relay/crypto.js, src/router/routes.js, src/store/modules/chats.js, src/store/modules/contacts.js, src/store/modules/wallet.js, src/utils/formatting.js, src/utils/image.js, src/utils/notifications.js, src/wallet/helpers.js, src/wallet/index.js, src/workers/xpriv_generate.js, test/jest/__tests__/crypto.test.js
Replace all non-mutable let declarations with const
=> Replace all non-mutable let declarations with const

src/components/dialogs/ClearHistoryDialog.vue, src/components/dialogs/DeleteChatDialog.vue, src/store/modules/chats.js
More cleanup to the chats store to remove duplicate processes.
=> Remove some excess actions from the chats store

src/components/panels/ContactPanel.vue, src/pages/Chat.vue, src/store/modules/chats.js
As per title. No strings allowed!
=> Ensure stamp amounts are stored as numbers

src/boot/setup-apis.js
A newer eslint caught a few errors with the keepalive hacks for the
Electrum client. The gist is that async functions were not being handled
correctly. This commit addresses those.
=> Fix errors in electrum server keepalive caught by eslint

src/relay/client.js
We were previously using `var` to get at try/catch variables. However,
this is bad practice as the variables *may not* be defined. This commit
properly moves dependent code up into the try/catch and switches from
`var` to `const`. (Additionally, there's a few eslint ignores thrown in)
=> This eslint errors in relay client

src-electron/main-process/electron-main.js, src/components/Profile.vue, src/components/chat/ChatMessage.vue, src/components/dialogs/ProfileDialog.vue, src/components/dialogs/SendAddressDialog.vue, src/components/setup/ChooseRelayStep.vue, src/components/setup/ProfileStep.vue, src/components/setup/SeedStep.vue, src/components/setup/SettingsStep.vue, src/pages/Setup.vue, src/store/index.js
In order to allow for building (kinda necessary) with the new eslint
configuration. This commit bulk fixes a number of eslint errors.
=> Large set of bulk es-lint fixes to the codebase

src/relay/client.js
Currently, the relay client refresh locks the client up. This locking
happens because the event loop is only allowed to process an event on
io, or by explicit yielding. This commit ensures the event loop is
yielded to every 5 messages that are processed. This allows the GUI
to keep responding to user input, and appear to have loaded immediately.
=> Ensure relay client is allowing JavaScript eventloop to tick

src/utils/constants.js
**Motivation**
These two servers regularly disconnect and stay down for long periods of time.
=> Remove problem electrumX servers

src/store/modules/chats.js
Currently, we are reloading all the state from the relay server.
We are also not showing read messages as "unread" now that we are
storing `lastRead` time properly. However, the desktop notifications
are still firing. This commit fixes that by checking last read for a
given contact when looking to send a desktop notification.
=> Ensure notifications aren't sounding for already seen messages

src/components/chat/ChatMessage.vue, src/components/context_menus/ChatMessageMenu.vue
=> Fix resend

src/components/dialogs/ProfileDialog.vue, src/pages/Setup.vue
**Motivation**
Some of the errors weren't firing correctly.
=> Fix error notifications

src/components/chat/ChatListItem.vue, src/components/chat/messages/ChatMessage.vue, src/components/chat/messages/ChatMessageText.vue
On mouseover display the stamp and specific time for each message and adjust hover color.
=> Switch to v-show information rather than tooltip

src/components/chat/ChatList.vue, src/components/chat/messages/ChatMessage.vue, src/components/chat/messages/ChatMessageReply.vue, src/components/chat/messages/ChatMessageStack.vue, src/layouts/MainLayout.vue, src/pages/Chat.vue
Some tweaks to the visual style of borders:
* Improve border colors 
* Refactor out `<style />`
* Move buttons
=> Improve styling of chat messages, borders and headers

src/components/chat/messages/Announcement.vue, src/components/chat/messages/ChatMessage.vue, src/components/chat/messages/ChatMessageReply.vue, src/components/chat/messages/ChatMessageStack.vue, src/components/context_menus/ChatMessageMenu.vue, src/components/dialogs/DeleteMessageDialog.vue, src/pages/Chat.vue
**Motivation**
By adding stricter type constraints we are less susceptible to various types of bugs.
**Implementation**
* Type constraints have been added on various of props relating to messaging. As a result we've identified and fixed a delete on resend bug.
* The announcement message diverged to such an extent from the other messages that we've made it it's own component.
=> Stricter type constraints surrounding messages

src/pages/Chat.vue
**Motivation**
First message of a chat was being duplicated.
=> Fix first message duplication

src/layouts/MainLayout.vue, src/pages/Chat.vue
Tweak border style to improve look and feel.
=> Tweak border style

src/pages/Chat.vue
Fixes off-by-one bug introduced by https://github.com/cashweb/stamp/pull/210
=> Fix off-by-one delete

src/components/chat/ChatListItem.vue, src/components/chat/messages/Announcement.vue, src/components/chat/messages/ChatMessage.vue, src/pages/Chat.vue
Improves look and feel of the dark mode messages and chat list items.
=> Improve dark mode

package.json, src/components/chat/ChatInput.vue, yarn.lock
=> Simplify emoji selection

src/relay/client.js
Currently, if a UTXO is invalid (due to sending a P2PKH or something),
a failure results when sending a message. However, there is no automatic
cleansing of spent UTXO. This PR attempts to remove any invalid UTXOs,
and then retry up to 3 times.
=> Try to automatically retry failed messages

src/components/Settings.vue, src/components/dialogs/ContactBookDialog.vue, src/components/dialogs/NewContactDialog.vue, src/components/dialogs/SendAddressDialog.vue, src/components/dialogs/SendBitcoinDialog.vue
Auto focus on inputs where needed.  Added ability to press enter after filling in a user's address to add them as a contact.  I wasn't sure if we would want to do that for the Send to Address menu since that's a little more risky.  I'll create another story to allow up and down arrows to navigate better when searching for a contact.
=> Better input box automatic selection

src/pages/Chat.vue
Due to a previous change, the floating scroll button was broken. This
commit fixes the event handlers to properly update the `bottom` data
value for the chat. Additionally, we are no longer using
`ScrollObserver` as the `ScrollArea` has it's own event which is more
accurate and responsive. It also properly fires on resizing the
scroll area, allowing for adjustments when `v-show` is updated.
=> Fix floating button behavior of chats

quasar.conf.js, src/components/chat/ChatInput.vue, src/components/chat/ChatListItem.vue, src/components/chat/messages/ChatMessage.vue, src/components/chat/messages/ChatMessageReply.vue, src/css/app.sass, src/css/app.scss, src/css/dark-mode.scss, src/css/light-mode.scss, src/css/quasar.variables.sass, src/pages/Chat.vue
This commit attempts to clean up darkmode while updating the color
scheme to not require darkmode conditional. This will make it easier
for us to try various color schemes, or update the pallets in general.
=> Attempt to update background colors and remove conditionals

src/store/modules/chats.js, src/store/modules/contacts.js
Add both Harry Barber, and Shammah Chancellor to the default contacts
so that new users have some initial people to talk to.
=> Add two default contacts for new users

src/components/Settings.vue, src/components/dialogs/ContactBookDialog.vue, src/components/dialogs/NewContactDialog.vue, src/components/dialogs/SendAddressDialog.vue, src/components/dialogs/SendBitcoinDialog.vue, src/pages/Chat.vue
Two lint errors slipped into master. This commit fixes them. We should
prioritize adding linting to circle so this doesn't continue to happen.
=> Fix two lint errors blocking build

src/components/Settings.vue, src/components/dialogs/ContactBookDialog.vue, src/components/dialogs/NewContactDialog.vue, src/components/dialogs/SendAddressDialog.vue, src/components/dialogs/SendBitcoinDialog.vue, src/layouts/MainLayout.vue
- move contactBookOpen to global store so there's a single source of
truth and so that the MainLayout has the ability to open the contact
modal with cmd+k
Thank you for contributing to Stamp! We really appreciate it. Our mission is to spread P2P electronic cash to the world. 
Please note, due to common industry practices of re-packaging open source software by for-profit business, we have an unusual software license. This license provides open access to the software source code, and reproduction thereof by community (non-commercial) projects, but excludes use of reproductions, and repackaging, by other for-profit organizations.
As such, by opening this pull request you acknowledge that you are providing the owners of this project an unlimited license to use and reproduce your …
=> Add cmd+k shortcut to open contacts

src/components/contacts/ContactItem.vue, src/components/contacts/ContactList.vue, src/components/dialogs/ContactBookDialog.vue, src/components/panels/SettingsPanel.vue, src/css/dark-mode.scss, src/css/light-mode.scss
I could use some feedback on whether or not I'm going in the right direction.  With this change the search functionality stopped working but I'm not sure why.  I've tried a few different approaches so far.
=> Use arrow keys in contact search dialog

.gitmodules, src/keyserver/proto/addressmetadata.proto, src/pop/proto/bip70.proto, src/pop/proto/paymentrequest.proto, src/pop/proto/wrapper.proto, src/relay/proto/filters.proto, src/relay/proto/messaging.proto
**Motivation**
We no longer want to use git submodules. 
In the future we'll migrate to perhaps using version numbers at the top of .proto files.
=> Remove git submodules

yarn.lock
=> Upgrade npm modules

src/adapters/vuex-relay-adapter.js, src/components/context_menus/ChatMessageMenu.vue, src/components/dialogs/DeleteMessageDialog.vue, src/components/dialogs/NewContactDialog.vue, src/components/dialogs/SendBitcoinDialog.vue, src/components/dialogs/SendFileDialog.vue, src/components/panels/ContactPanel.vue, src/components/panels/SettingsPanel.vue, src/keyserver/handler.js, src/layouts/MainLayout.vue, src/pages/Chat.vue, src/relay/client.js, src/store/modules/chats.js, src/store/modules/contacts.js, src/utils/formatting.js, src/wallet/index.js
More effort to settle on consistency in the codebase. Some places used
address, and some used addr. It is better to type a bit more, and just
always agree nobody will make up their own abbrevations.
=> Switch to using `address` over `addr`

src/components/chat/messages/ChatMessageReply.vue, src/components/setup/DepositStep.vue, src/layouts/MainLayout.vue, src/relay/client.js, src/store/modules/wallet.js, src/wallet/index.js
A few of these logs are very unnecessary now. Remove spammy logs and
make a few others more consistent.
=> Clean up some logs

src/components/dialogs/NewContactDialog.vue
=> dont close new contact dialog on field click

src/layouts/MainLayout.vue, src/store/modules/chats.js
**Motivation**
People should be able to immediately see how many unread messages they have from their desktop. This adds a badge to dock icons to allow for that.
=> Add badge on dock icons

quasar.conf.js, src/components/dialogs/ContactBookDialog.vue, src/components/dialogs/NewContactDialog.vue, src/components/dialogs/ProfileDialog.vue, src/components/dialogs/RelayConnectDialog.vue, src/components/dialogs/SeedPhraseDialog.vue, src/components/dialogs/SendAddressDialog.vue, src/components/dialogs/SendBitcoinDialog.vue, src/components/dialogs/SendFileDialog.vue, src/components/dialogs/SettingsDialog.vue, src/components/dialogs/TransactionDialog.vue, src/components/dialogs/WalletDialog.vue, src/css/dialogs.scss
Improve consistency across dialogs.
=> Improve consistency across dialogs

src/relay/client.js, src/wallet/index.js
* Add missing await in `deleteOutpoint`.
* Add missing await before `getOutpoint`.
* Enforce consistency to the format of `address` property prior to putting outpoints.
=> Various fixes

src/layouts/MainLayout.vue, src/store/modules/chats.js, src/store/modules/contacts.js, src/utils/constants.js
**Motivation**
For some unknown reason the default contacts weren't adding correctly, perhaps due to reactivity. Fixes https://github.com/cashweb/stamp/issues/258
**Solution**
Include actions to add default contacts and then use it on startup.
=> Fix default contacts

src/components/setup/DepositStep.vue
**Motivation**
Incorrect import was causing failure when opening external browser.
=> Fix faucet link

src/components/dialogs/NewContactDialog.vue
i'm not sure how i goofed the last fix, but here we are
=> actually fix new contact dialog

src/components/chat/ChatList.vue
**Motivation**
Fixes https://github.com/cashweb/stamp/issues/232
=> Improve UX around status buttons

src/store/modules/chats.js
Previously, trailing outbound messages would be counted as unread on
load. This commit ensures that these messages are not errorneously
counted as unread.
Fixes #285
=> Fix unread counts on load

src/wallet/index.js
This commit fixes some performance issues around generating stamp
and stealth transactions by pre-loading and updating all the UTXO data.
=> Fix step in fixing transaction generation slowness

src/relay/storage/level-storage.ts, src/types/level/level.d.ts, src/types/level/leveldb.d.ts, src/wallet/storage/level-storage.ts
Add type definitions for level module and fixup code required to
support the (now) defined types.
=> Add type definitions for level module

src/relay/client.js, src/wallet/index.js
Somehow we are trying to reuse UTXOs twice. This commit adds some
logging and attempts to ensure that UTXOs are properly frozen.
=> Attempt to fix more edge cases around frozen UTXOs

src/wallet/index.js
Due to deterministic coin selection, sometimes the wallet can get "stuck." This is undesirable during error retries. This commit ensures that a new UTXO will be selected each time constructing a transaction set is retried. This has a beneficial effect on chainalysis as well in some regards. Previously, sometimes revealed the total amount sent if there was a UTXO larger than the current one. This ensures we sometimes do select a random UTXO for small amounts.  However, there is more work to be done to ensure transaction set building is more anonymous.
=> Use random UTXOs instead of specific sizes.

src/wallet/index.js
In order to ensure that amounts are obfuscated, as well as stamps, we
now ensure that there are at least two iterations of the transaction
set builder. Each iteration is given a randomized amount bewteen
`[minimumOutputAmount, amount]`. This ensures that we won't reveal an
amount when there is a UTXO larger than the amount we were intending to
send.
=> Ensure there are at least two transactions in a transaction set

src/wallet/index.js
In a previous commit, we removed support for generating more than
1 change transaction per txn. This was done because the old change
generation code made it very obvious which output was being sent to
another person. However, this is undesirable because we
want to extra UTXOs so we do not hit chain limits. This commit adds
this functionality support for generating multiple change outputs, but 
with a mechanism to appropriately obfuscate the actual output from
the change.
=> Add support for multiple change outputs back to tx construction

src/relay/client.js
The next release switches relay servers which will not have profiles for
the users created. This commit adds automatic profile recreation when
attempting to download messages.
=> Allow for client to automatically recreate profile on new servers

src/wallet/index.js
The electrum-cash library was changed to automatically resubscribe to
all script hashes. As part of this, it also throws an exception if there
are any event listeners that aren't registered in the map of listeners
and params. This commit removes the need to have a single listener
on the entire connection object. Instead, we now let the internal
logic for the electrum-cash client handle this.
=> Fix subscription handling due to a different change in electrum-cash API

local_modules/bn.js/README.md, local_modules/bn.js/lib/bn.js, local_modules/bn.js/package.json, local_modules/bn.js/util/genCombMulTo.js, local_modules/bn.js/util/genCombMulTo10.js, package.json, quasar.conf.js
BN.js has a bug where it tries to replace Buffer object, but is in fact
breaking it. Newer browsers and node both have this object as a global.
The polyfill actually clobbers it.
=> Ensure fixed bn.js is packed

src/keyserver/handler.js, src/relay/client.js, src/store/index.js, src/wallet/index.js
=> Clean up some console logs

tsconfig.json
This is required to resolve an issue... Which I no longer remember. Doh
=> Change ts target so we can use some additional funcitonally

src/utils/constants.js
=> Add our own testnet fulcrum server to list of defaults

quasar.conf.js
=> Add sourcemap support to webpack for debugging purposes

src/components/chat/ChatInput.vue
The input bar had too much junk in it for mobile use. This commit
moves it all to a menu ala telegram.
=> Fixup chat input for mobile use

src/components/chat/ChatList.vue, src/components/panels/LeftDrawer.vue, src/layouts/MainLayout.vue
A bunch of lint errors made it through when refactoring some components
for mobile. Clean them up.
=> Fix linter errors that made it through quality control

src/wallet/index.js
We want to allow people's initial paying transaction to also reveal
their identity. That way, when a friend sends you money to create an
account, they can immediately add you to their contact list. This commit
fixes what was previously an oversight -- We had change the deposit ux
to use this address, but had not updated the subscriptions to function
with this address which was previously different.
=> Fix subscriptions around the identity in the sign up flow

src/relay/client.js
Due to a previous refactor, when message bodies were plucked off
websocket notifications, they were not being used in the client. The
data was being downloaded, but not used for the purpose of loading
up the message contents.
=> Fix issue where parsed messages were not being used by the client

src/relay/client.js
As per title. Switch from `else if` to standard `ifs` for clearer
line breaking and indentation.
=> Fix some style issues with the message entry processing loop

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
This pr adds a basic vscode dev container which enables local development inside a container
=> create dev container

src/components/chat/messages/ChatMessage.vue
=> Fix DeleteMessageDialog import in ChatMessage.vue

src/cashweb/keyserver/handler.ts
This factors out the message parse body as well as implementing the
`GET /messages/:payloadDigest` API which will allow deep linking to
specific posts.
=> Implement fetching individual messages

src/cashweb/keyserver/broadcast_pb.d.ts, src/cashweb/keyserver/broadcast_pb.js, src/cashweb/keyserver/handler.ts, src/cashweb/keyserver/proto/broadcast.proto, src/cashweb/types/agora.ts, src/components/agora/AgoraMessage.vue, src/components/agora/AgoraMessageReplies.vue, src/pages/Agora.vue, src/pages/AgoraPost.vue, src/pages/CreatePost.vue, src/router/routes.ts, src/store/modules/agora.ts
Basic implementation of Agora reply system with a page to navigation
directly to a post to see all the replies. This also allows deep linking
from other websites into agora posts!
=> Implement replies and deep linking to posts

src/pages/CreatePost.vue
`v-if` was not properly on the root block of this card.
=> Remove "In reply to" from CreatePost.vue when it's not a reply

src/pages/CreatePost.vue
Currently the backend is the only thing responsible for post validation on Agora.
This adds some basic feedback to users prior to getting backend errors.
=> Add some basic form validation on Agora post creation

src/cashweb/keyserver/handler.ts
=> Extend Agora Post timeframe from 1 day to 1 week

src/cashweb/keyserver/handler.ts, src/cashweb/types/agora.ts, src/components/agora/AgoraMessage.vue
Show formatted message timestamp next to the topic.
=> Display timestamp of message on the feed

src/store/modules/agora.ts
=> Remove several log lines which print large amounts of data

src/store/modules/agora.ts
=> Only fetch recent messages when refreshing the Agora

src/pages/Agora.vue
=> Remove extraneous stuff from Agora.vue

src/store/modules/forum.ts
Implement a half-life on post votes for sorting. Older posts lost half
of their votes every day they've aged.
=> Vote sort decaying on amount/timestamp

src/layouts/ForumLayout.vue
Add a create post button back to the Forum title bar per request,
and fix the formatting of the other buttons to save some space for
a better mobile experience.
=> Update butons on Forum title bar

src/pages/Chat.vue
Scroll got re-broken yet again when refactoring the chat screen. Put
back in place the code to properly handle scrolling on a new message.
=> Fix scrolling behavior in chat on new messages

src/layouts/ChatLayout.vue, src/pages/Chat.vue
Handles and events for these actions got mixed up in the recent reactor.
Put them back in their proper places and bubble up events properly.
=> Fix Reply, Send File, and Give Lotus Actions

src/layouts/ForumLayout.vue
=> Remove forum icon from title bar in Forum screen

src/css/app.scss
|Before|After|
|---|---|
|<img width="683" alt="Screen Shot 2021-11-14 at 8 13 33 AM" src="https://user-images.githubusercontent.com/4146037/141682539-39ef41af-ef5a-4b53-9796-9c73581633de.png">|<img width="679" alt="Screen Shot 2021-11-14 at 8 08 11 AM" src="https://user-images.githubusercontent.com/4146037/141682557-1f8e7d9a-2a43-4242-a2e3-601a0a003734.png">|
=> Change header color to white

src/components/forum/ForumMessage.vue, src/css/app.scss
|Before|After|
|---|---|
|<img width="1360" alt="Screen Shot 2021-11-14 at 12 33 13 AM" src="https://user-images.githubusercontent.com/4146037/141669003-2c2a9bce-72c5-4232-b894-5ad07614e757.png">|<img width="961" alt="Screen Shot 2021-11-14 at 12 32 16 AM" src="https://user-images.githubusercontent.com/4146037/141669029-2373422e-4f63-4723-99da-7ea6c5606542.png">|
=> Update post ux

src/cashweb/keyserver/handler.ts, src/components/panels/ForumDrawer.vue, src/pages/Forum.vue, src/store/modules/forum.ts, src/utils/sorting.ts
This commit adds some options to have a minimum vote threshold, a
duration for loading messages, and optional sort orders. This is a
fairly minimal set of options, and can be extended over time.
=> Add some configurability to the Forum feed

src/utils/sorting.ts
Sort by absolute number of votes over the time frame provided.
=> Add `top` sort to Forum

src/components/forum/ForumMessage.vue, src/pages/CreatePost.vue, src/pages/ForumPost.vue
|Before|After|
|---|---|
|<img width="798" alt="Screen Shot 2021-11-14 at 7 38 56 PM" src="https://user-images.githubusercontent.com/4146037/141705843-df50527f-afaa-48df-aa76-016b612d252f.png">|<img width="751" alt="Screen Shot 2021-11-14 at 7 38 38 PM" src="https://user-images.githubusercontent.com/4146037/141705858-92301a8d-4e41-4871-aa63-b2425e747325.png">|
=> Fix post margin

src/components/forum/ForumMessage.vue
|Before|After|
|---|---|
|<img width="324" alt="Screen Shot 2021-11-14 at 8 15 22 PM" src="https://user-images.githubusercontent.com/4146037/141707559-5a2d390c-4411-4b91-b3f3-6ff93fef2567.png">|<img width="324" alt="Screen Shot 2021-11-14 at 8 18 38 PM" src="https://user-images.githubusercontent.com/4146037/141707809-bb54ce88-7ec2-4f21-a2bc-76f7d3116ef5.png">|
=> Fix width on small devices

src/components/forum/ForumMessage.vue
=> Use percent instead of vw

src/cashweb/relay/index.ts, src/cashweb/wallet/index.ts
Currently, both are a `Record` by address, but never addressed by address, therefore a list is sufficient.
This can later be refactored further for switching to Chronik.
=> `Wallet`: Refactor `addresses` & `changeAddresses`

src/cashweb/wallet/index.ts
Currently, this uses Electrum's WebSocket interface. This switches it to use Chroniks, getting us one step closer to removing the dependency on Electrum completely.
=> Use Chronik Indexer to subscribe to new messages

src/cashweb/wallet/index.ts
Somehow this slipped local type checking and CI lint.
=> Remove `electrum-client` dep from wallet/index.ts

package.json, src/cashweb/relay/index.ts, yarn.lock
This prevents accidentally burning txs if not all txs are accepted into the mempool.
=> Use atomic `ChronikClient.broadcastTxs`

src/layouts/MainLayout.vue
Request notification permission to ensure notifications can be displayed to user.
=> Request notification permission

src/components/chat/messages/ChatMessageText.vue, src/components/forum/ForumMessage.vue, src/pages/CreatePost.vue, src/utils/markdown.ts
* Update markdown renderer configuration to allow color changes in
darkmode, as well as custom
* Add a purify function to be used later when rendering replies.
=> Update markdown renderer configuration

src/components/chat/ChatList.vue, src/components/chat/ChatListItem.vue
As per title. Fixes a rendering issue
=> Update formatting in the ChatList

.vscode/settings.json
=> Fix vscode settings around constructor formatting

src/store/modules/chats.ts
The findIndex functionality is searching for the wrong information
in chats.ts and this is causing it to not properly remove the message
from being displayed, even though it
=> Fix deleting of messages in local storage

src/store/modules/chats.ts
Incorrectly named variable corrected.
=> Fix naming of `apiAddress` in chats.ts

src/components/chat/ChatList.vue, src/components/chat/ChatListItem.vue, src/layouts/MainLayout.vue, src/pages/AddContact.vue, src/store/modules/chats.ts, src/utils/notifications.ts
* Fix setting of active chat address so notifications can
be shown correctly.
* Fix notification requests
* Improve notification preview of messages
=> Fix notifications and ensure non-text messages are shown in preview

src/cashweb/relay/index.ts, src/layouts/ChatLayout.vue, src/pages/Chat.vue
=> Convert Chat components to typescript

src/cashweb/wallet/index.ts
Dist limit is around 1000 sats now.
=> Update dust limit in wallet

src/stores/contacts.ts
Ensure pubkeys are correctly serialized on save.
=> Fix key saving and restoring of contacts

src/components/setup/AccountStep.vue, src/i18n/en-us/index.ts
Remove cute phrasing from when we were trolling.
=> Change wording during account setup

src/pages/Chat.vue
=> scrollToMessage: run debounced function

src/boot/setup-apis.ts
=> Pinia fixes

src/components/panels/ForumDrawer.vue
=> use storeToRefs for ForumDrawer reactivity

src/stores/contacts.ts
In some instances, old pubkeys fail to deserialize due to type errors
that existed prior to Pinia. We fixed most of the backwards
compatibility, however some contacts are still in a weird format for
user with data stored for quite awhile.
=> On load, ignore contacts which are corrupt

src/components/forum/ForumPost.vue, src/components/panels/ForumDrawer.vue, src/pages/Forum.vue, src/stores/forum.ts
Remove previews, and change theme to look more like old reddit and
hackernews.
=> Experiment with a new theme for the front page of the forum

src/boot/setup-apis.ts, src/cashweb/keyserver/index.ts, src/cashweb/types/forum.ts, src/components/chat/ChatList.vue, src/components/topic/TopicDrawer.vue, src/components/topic/TopicInput.vue, src/components/topic/TopicListLink.vue, src/components/topic/TopicMessage.vue, src/i18n/en-us/index.ts, src/layouts/TopicLayout.vue, src/pages/AddTopic.vue, src/pages/Topic.vue, src/router/routes.ts, src/stores/topics.ts
Definitely not ready to merge, but it "kinda" works. Still need the ability to subscribe to topics, and change the posting and filtering rate.
=> Topics: Milestone 1

src/pages/Changelog.vue
Was causing scroll bars to unnecessarily show up.
=> Remove excess padding from Changelog

src/components/topic/TopicMessage.vue, src/stores/topics.ts
Adds minimal support for voting on topic messages. However, users which
already downloaded the message will not likely see the update to
existing votes. This should be fine for now, but ideally users get
updated and the votes change automatically when other users vote on
them.
=> Add support for voting on topic messages and format name links

src/components/topic/TopicInput.vue, src/layouts/TopicLayout.vue
Simple addition of a button for users who don't know that "return" will
send the message.
=> Add a send button to the topic input box

src/layouts/TopicLayout.vue
=> Disallow accidental sending of empty messages

src/stores/topics.ts
It seemed like there was an issue with message loading because the
starting point for loading messages in a topic depended on specific code
paths for how the topic was initialized. This commit fixes the code so
that each code path uses the same `lastUpdate` to initialize a topic.
=> Ensure starting topic load date is consistent across code

src/i18n/en-us/index.ts, src/pages/Settings.vue
Fix converting back and forth between minutes and reactivity.
=> Fix several issues with the settings pages

src/layouts/TopicLayout.vue
Switch from a burger to a settings gear...
=> Fix icon for topic settings

src/utils/sorting.ts
Fix sort date sort ordering which was reverse of what is should be.
=> Fix forum sort

package.json, yarn.lock
Update deps to the latest quasar and electron.
=> Upgrade quasar and electron

src/components/SubscribeDialog.vue, src/layouts/MainLayout.vue, src/stores/appearance.ts
Add a welcome dialog which appears every 10 days, with links to our
discord and patreon page.
=> Add a welcome dialog and links

src/App.vue
Automatically add topics based on IP localization, so that people can
hopefully find individuals close to them to meet up for coffee, or buy
and sell other goods.
Closes #613
=> Add a prototype of automatically adding localized topics

src/components/StatusFooter.vue, src/components/chat/ChatListLink.vue, src/components/chat/messages/ChatMessage.vue, src/components/chat/messages/ChatMessageImage.vue, src/components/chat/messages/ChatMessageStack.vue, src/components/chat/messages/ChatMessageStealth.vue, src/components/chat/messages/ChatMessageSuffix.vue, src/components/chat/messages/ChatMessageSuffixButtons.vue, src/components/chat/messages/ChatMessageText.vue, src/components/contacts/ContactList.vue, src/components/dialogs/ImageDialog.vue, src/components/dialogs/RelayConnectDialog.vue, src/components/dialogs/TransactionDialog.vue, src/components/panels/ContactCard.vue, src/components/setup/AccountStep.vue, src/components/setup/EULAStep.vue, src/layouts/SetupLayout.vue, src/pages/Changelog.vue, src/pages/Send.vue, src/types/bitcore-lib-xpi/bitcore-lib-xpi.d.ts
Convert the remaining javscript components to typescript and fix various
type errors which were revealed. Also, clean up some various code that
was not needed.
=> Convert the last of the components to typescript

src/components/forum/ForumMessage.vue, src/components/forum/ForumPost.vue, src/stores/forum.ts, src/utils/sorting.ts
Show message bodies by default, and fix bugs with sorting of posts to make "This week in Stamp" easier to produce.
=> Adjust legacy forum to make it easier for "This week in Stamp"

src/cashweb/wallet/index.ts
Since we switched to the Chronik API, we have all the data available to update our UTXO set without refreshing the entire transaction history for an address.
=> Optimize UTXO set update when a subscription is hit

src/components/setup/DepositStep.vue
=> Remove faucet link from signup screen

src/App.vue
This is obnoxious and results in me getting all kinds of topics on the left hand side. Delete them for now, maybe we'll add something better in later.
=> [topics] Remove setting up default topics based on IP address

src/pages/Setup.vue, src/stores/contacts.ts, src/utils/constants.ts
Lots of random constants that didn't seem to ever get used or were needed were left in here. Clean them out.
=> [chore] Clean up constants file

src/cashweb/wallet/index.ts
We're currently checking transactions that have multiple change outputs we're subscribed to many times. This is spammy and makes it hard to debug other problems.
=> Don't re-check already checked TXIDS on subscription hits

src/cashweb/relay/index.ts, src/cashweb/wallet/index.ts
In order to ensure local UTXO state matches the blockchain we excessively sync UTXOs on message sends or receives. Sometimes this causes a UTXO to be deleted twice (which is intended behavior) but certain code paths would cause this to improperly fail and generate an exception. Other upstream code would then fail in inappropriate ways.
Additionally, the retries on message sending not properly handling errors and retries.
This commit should fix both of those issues.
=> [bugfix] Handle issues around deleting UTXOs on 50x errors

package.json, src/cashweb/wallet/index.ts, yarn.lock
=> [npm] Update chronik-client to the latest version

src/components/chat/messages/ChatMessage.vue
=> Use server timestamp vs received timestamp

src/utils/constants.ts
Shammah was feeling lonely in that array, so I took a poll and added more people per his request.
=> Add more default contacts
