StampChat/stamp

src/store/index.js

Currently, we are persisting the entire state every time a key is
pressed. This is leading to a significant slowdown while typing
if there are any messages at all to be persisted. This commit adds
a filter to the vuex-persist plugin to only persist when certain
mutations are called.
This is a first pass at what mutations should trigger a persist. Future
work should look more closely at this and see if we cannot attach
the vuex-persist to only relevant stores.

Ensure we only persist state on important changes

---

src/components/chat/ChatList.vue

Add a scrollbar to the chatlist so that having large numbers of
contacts doesn't cause rendering problems. Currently, if you have more
than around 10 contacts, you start being able to scroll into white
space as the chat and chatlist are attached to one another. It looks
very unprofessional.

Add scrollbar to chatlist

---

src/components/chat/ChatList.vue
src/store/modules/chats.js

Currently, the chatlist is sorted by order that you that contacts
were added via either sending or receiving messages. However, the
point of using this chat client is to be able to prioritize senders
who value your time.
This commit changes the sort order to be based on total unread value
of the messages you've been sent.

Sort chatlist by how much "unread" money a contact has sent

---

src/components/chat/ChatList.vue
src/store/modules/chats.js

Previously, there was no tie-breaker for chats that were read. However,
it did pull the selected chat to the top of the list. This caused the
UI to be a little jumpy. To fix this, we sort any chats that have
the same values by the last time their chat was read.

Fix chatlist sorting to sort read chats by last read time

---

src/components/chat/ChatList.vue
src/components/chat/ChatListItem.vue
src/store/modules/chats.js

Currently, we were only displaying the total number of unread sats.
This was somewhat unwiedly for large numbers, and it wasn't clear
to users what the number was intended to be. This commit adds the
appropriate currency formatting, and also adds back another chip which
shows the total number of unread messages.

Format unread value to have units and add back total unread messages

---

README.md

Remove excess `s` from the `git submodule` command instruction

Fix typo in `git submodule` command

---

src/store/index.js

This goes off every few seconds, and really slows down the system when
the entire state is written for every contact updated. This seems rather
excessive to cause a persistence run since we can do it after the wallet
restarts anyways.

Don't blit state to disk when running updateContact

---

src/store/modules/chats.js
src/store/modules/wallet.js

Previously, we used a simple digest of the payload to generate the
stamp private key. However, we changed this since we now allow
stamps to have split outputs. This commit updates the sending
portion of the client to properly calculate stamp privkeys when
spending them.

Ensure stamps privkeys are generated using the new digest protocol

---

src/pages/Setup.vue
src/utils/constants.js

Our previous electrum server switched to TLS and changed port. This
commit changed the default server, as well as changed some of the values
to be in the constants files.

Ensure eletrum port and protocol is configurable in constants files

---

src/store/modules/chats.js
src/store/modules/wallet.js

This commit moves the UTXO private key generation to were messages
are received and decoded, rather than placing them in the wallet. This
allows better decoupling of concerns and makes it so you don't
need to add logic to two places every time we add a new message type.

Deouple message handling logic from wallet

---

src/store/modules/chats.js

This variable was accidentally removed in a previous commit, however
it is needed in order to be able to spend the UTXO later.

Ensure outputIndex is set in the UTXO

---

src/store/modules/chats.js

For some reason, the relay server is sending an invalid message payload
occasionally. This commit swaps the deserialization in a try/catch block
so that we can continue to read further messages.

Catch error on deserializing message payload and continue

---

src/relay/constructors.js
src/store/modules/chats.js

Leaving payloadDigest as a string causes protobuf serialization errors.
This commit addresses that problem by first turning it into a buffer
before setting the key.

Make sure reply payload is a buffer before trying to serialize

---

src/store/modules/chats.js

This commit fixes the getter call for the reply digest when receiving
messages.

Fetch reply digest from reply entry using correct getter

---

src/relay/constructors.js
src/store/modules/chats.js
src/store/modules/wallet.js

In an effort to obfuscate transaction amounts, we have added bundling
to the stealth entries. This allows transfered amounts to be split
over multiple bitcoin cash transactions.
This commit adds support for the new protobuf specification that allows
that. It supports on the receiving end arbitrary splits, but on the
sending end only does one output and one transaction currently.

Update stealth txn processing for new proto specs

---

src/relay/constructors.js
src/relay/crypto.js
src/store/modules/chats.js

In an effort to obfuscate transaction amounts, we have added bundling
to the stealth entries. This allows transfered amounts to be split
over multiple bitcoin cash transactions.
This commit adds support for the new protobuf specification that allows
that. It supports on the receiving end arbitrary splits, but on the
sending end only does one output and one transaction currently.

Use new crypto scheme for stealth transaction keys

---

src/store/modules/chats.js

This commit changes the iteration style so that the type of the
indices are integer, and not string. This was causing derivation to
blow up in a later commit.  Also ensure that toBuffer is called rather
than compared. It's unclear how this worked in the wild.

Fix various type issues with Stamps and Stealth transactions

---

src/store/modules/chats.js

Minor refactor. Current code uses branching multiple places rather
than defining a cost. This commit just cleans that up.

Simplify recipient-address dependent blocks in message processing

---

src/store/modules/chats.js

When a received payload was truncated by the server, this code
woudl only work when it was from yourself. It did not work when
other users were sending you messages due to token validation.

Ensure payload is fetched from correct location

---

src/store/modules/chats.js

Currently, we were only counting the output amounts when receiving
messages. This was causing a number of errors due to address validation
and totals were not displaying when we reimpoted the wallet.

Fix UTXO filtering during stealth txn processing

---

src/relay/constructors.js
src/relay/crypto.js
src/store/modules/chats.js
src/utils/constants.js

The new protocol uses BIP32 derivation for finding out the keys for
each UTXO and transaction. This is less bespoke and has off the shelf
libraries for the calculation. It should make lives easier in the future
for other implementers.

Change protocol for determining stamp UTXO keys

---

src/components/dialogs/SendAddressDialog.vue
src/pages/Setup.vue
src/pop/index.js
src/store/modules/wallet.js

Attempt to use only one UTXO if possible, and if not attempt to use
UTXOs from as few transactions as possible to avoid co-mingling marked
UTXOs.  Additionally, there's some miner logging fixups which were
required to debug this change.

Update UTXO selection for better privacy

---

src/relay/constructors.js
src/store/modules/chats.js

**Motivation**
We currently index messages by their payload digest. One was able to insert a buffer as a key into Vuex, however Vuex serialized these in a strange encoding - hence upon reload the payload digest would become some bizarre string.
To prevent this we've immediately serialized and deserialize from hex at the boundary of the Vuex store.
All crypto functions continue to take Buffer's as arguments and asserts have been setup to guard against strings being passed into them by accident.

Switch to hex encoded payload digests

---

src/components/chat/ChatInput.vue
src/pages/Chat.vue

This commit moves the chat input box into its own component so that
it may be duplicated in other parts of the code. It also removes
the dependencies on global state.

Turn the chat input into its own component

---

src/layouts/MainLayout.vue
src/store/modules/chats.js

Herin we render multiple chat components for each contact, but only
show the active one. This ensures these chats aren't re-rendered when
switching contacts. This is at the expense of memory and initial load
times. However, much of this can be obviated with more adjustments to
how vuex is being used.

Make chat area not re-render when switching tabs

---

src/components/chat/ChatList.vue
src/layouts/MainLayout.vue
src/pages/Chat.vue

This commit removes the need to pass around and use tabHeight within
the components of the layout by ensuring the outer containers are all
set to max height. Additionally, the q-page component is set to the
maximum size view a `style-fn` which receives the viewport header/footer
size as an offset.

Remove use of tabHeight to fix heights in layout

---

src/pages/Chat.vue

As per title. Use the correct reference for focusing the chat input.

Fix missed reference to old chat input

---

src/layouts/MainLayout.vue
src/store/index.js

As per title. Delete reference to clock and tabHeight.

Delete unused code leftover from previous cleanups

---

src/store/modules/chats.js

Currently, if you delete your state and reimport your key, your outboud
messages will not show a stamp price. This commit fixes that by ensuring
that these messages have their outpoints stored with them.

Ensure stamp prices are re-imported from seed on outboud messages

---

src/layouts/MainLayout.vue
src/pages/Chat.vue

Due to recent refactors, `activeChat` is no longer accurate for what
the prop of the Chat component represents. This commit renames it to be
simply `address.`

Rename `activeChat` to `address` as `activeChat` is inaccurate

---

src/components/chat/ChatMessage.vue
src/pages/Chat.vue
src/store/modules/chats.js

This commit removes the global vuex storage of active reply digests
and moves them into the local vuex component state. This removes
quite a bit of complexity from the chat store, as well as the other
components

Remove global reply state. Keep it inside the chat view

---

src/pages/Chat.vue
src/store/modules/chats.js

While changing the behavior of active chats, we inadvertantely broke
the unread message functionality. This commit fixes it by moving the
dispatch of readAll to the store, where the activeChat is switched.

Fix unread message functionality

---

src/store/index.js
src/store/modules/chats.js

This should allow migrating and rehydrating data more easily and quickly.
By doing it prior to replaceState, there won't be any nasty reactive
updates every time something is rehydrated.

Add a hack to enable state migrations

---

src/layouts/MainLayout.vue
src/store/index.js
src/store/modules/wallet.js

This commit moves the wallet rehydration to the vuex-persist layer
before any components are loaded. This avoids a bunch of reactive events
from being progressively fired.

Rehydrate wallet within the vuex-persist module before components loaded

---

src/pages/Chat.vue

When the time is updated, the height of the chatboxes are also
reactively updated. However, since the contents are not shown the
chat input has a height of zero. This causes the chat message box
to take 100% of the viewport. When switching back to hidden viewports
it takes awhile for it to update again. This looks bad.
As a temporary fix, we set the minimum value to 50 (which is the same)
as the chat input on most devices.

Fix reset of the chatarea height when not shown

---

src/layouts/MainLayout.vue
src/pages/Chat.vue

Currently, the scroll behavior is largely manual. This commit makes
the newly active chat scroll to the bottom if it is the at the top.
Additionally, when

Fix some aspects of automatic scrolling

---

package.json
src/keyserver/generate_protobufs.sh
src/pop/generate_protobufs.sh
src/relay/generate_protobufs.sh
yarn.lock

Two yarn commands were added: generate:protobuffers and clean:protobuffers. This was intended to facilitate development.
Now you don't need to have protoc globally installed, as it is installed locally with yarn and then executed locally on the scripts.

chores - add npm/yarn scripts to generate and clean protobuffers

---

src/components/dialogs/SettingsDialog.vue
src/layouts/MainLayout.vue
src/pages/Setup.vue
src/store/modules/contacts.js
src/utils/constants.js

This commit causes contacts to be updated when they are activated,
rather than on a timer. The update times are cached, and only repolled
when the timeout for a particular contact expires. This leads to less
requests against the backends overall.

Update contacts on demand rather than on a timer

---

src/store/modules/chats.js

Currently, we've been adding to unread message totals even when the
chat the messages are being received for is active. This commit fixes
that issue.

Don't add totals to unread if chat is active

---

README.md
package.json

Because we are not checking in the generated protobuf files, we no
longer need most contributors to install protoc or deal with submodules.
I've removed those instructions from the basic flow, and moved them
to the end, as they are only needed when the protos change.

Update readme to remove protobuf information

---

src/pages/Chat.vue
src/store/modules/chats.js
src/utils/notifications.js

**Motivation**
After some discussion, we concluded that it would be better to not throw out messages with insufficient fees.

Prevent notifications with insufficient fees rather than censor

---

src/layouts/MainLayout.vue

When importing an old wallet from seed, there is currently a race
condition between checking UTXO validity, and loading up the chat
history. As such, sometimes we end up in a state where we cannot
generate new valid transactions. This commit de-paralleles the
chat reload and wallet validation steps. A future commit can possibly
address these issues to enhance load times.

Fix race condition on re-load ordering

---

src/boot/setup-apis.js
src/components/chat/ChatList.vue
src/components/dialogs/ProfileDialog.vue
src/components/dialogs/RelayConnectDialog.vue
src/components/dialogs/SendAddressDialog.vue
src/components/dialogs/WalletDialog.vue
src/components/drawers/MyDrawer.vue
src/components/setup/DepositStep.vue
src/layouts/MainLayout.vue
src/pages/Setup.vue
src/pop/index.js
src/relay/constructors.js
src/store/modules/chats.js
src/store/modules/wallet.js
src/wallet/index.js

This commit removes the unnecessary wallet functionality from the wallet
Vuex store, and switches to using the wallet class which was introduced
in a previous commit. The long-term goal here is to get all the CashWeb
protocol interaction detangled from the Vue/Vuex code so that it can be
used in headless applications.

Migrate to using wallet class

---

src/store/modules/wallet.js

We no longer save the identity privkey as it is calculated on startup.
This commit removes a few dead lines.

Remove unused state from wallet vuex store

---

src/relay/client.js
src/wallet/index.js

Currently, we add all UTXOs we've received while syncing, and then
run through them vs the electrum server. This requires that we slam
the electrum server asking for histories for ever address we've ever
used. This is not scalable, and is particularly inefficient. Instead, we
can simply remove anything we've recorded as being spent from our UTXO
set.

Remove spend utxos while syncing

---

package.json
src/wallet/index.js
yarn.lock

Currently, we are resolving promises for some wallet operations all
at once. This can generate a storm of requests to electrum servers,
resulting in bans. This commit adds the `bluebird` library and uses its
`P.map` functionality with a concurrency parameter to limit this to
some extent.

Add `bluebird` library to limit promise resolution concurrency

---

src/wallet/index.js

There is a discrepancy between how private keys are stored in the `addresses` and `changeAddresses` fields of the wallet, which would cause occasional transaction construction errors.
Both have been changed to the following structure
```javascript
{ privKey }
```
and the `privKeys` getter changed in accordance.

Fix address object

---

src/relay/client.js
src/relay/constructors.js

Removing async where not necessary avoids bugs where a Promise would be
unexpecedtly returned from an API call which should not do any IO. As
such, this commit seeks to clean that up from the wallet and the payload
construction APIs.

Remove async/awaits from functions which are actually synchronous

---

src/wallet/index.js

Due to an error in a previous commit, we did not spawn listeners with
our chosen electrum server for change addresses. This caused various
problems when sending large UTXOs as outbound transactions (e.g. stealth
payments).

Ensure change addresses are also monitored

---

src/pages/Setup.vue
src/store/modules/contacts.js
src/utils/constants.js

**Motivation**
A few people had expressed problems when traversing the setup phase. The origin of these problems were due to lax validation on input fields.
**Changes**
- Add validation on Profile and Inbox data during setup.
- Split `defaultRelayData` in `pendingRelayData` and `defaultRelayData` - the former for a dummy contact profile used while adding contacts, the latter for an empty profile.

Improve setup validation

---

src/store/index.js
src/store/modules/wallet.js

This commit causes chat messages and other actions to not cause disk
writes. The only thing that are stored are necessary items to restore
state from the relay server. We need to figure out how to only store
chat messages in bulk once they are loaded. Possibly some timer to
autosave in the future.

Reset state of schema versions are different

---

src/components/dialogs/ProfileDialog.vue
src/pages/Setup.vue
src/store/index.js
src/store/modules/my_profile.js

Currently, ever global state change causes a blit to disk of the full
chat state. This makes the chat app slow. This commit removes all the
chat state local storage. Instead, we always load from remote state.

Remove chat state storage and remove blitting

---

src/components/chat/ChatMessage.vue
src/store/modules/chats.js

As per title.  This means when re-importing from the server we don't
see wildly off times for messages.
Closes #74

Use server time for display and unread messages instead of receivedTime

---

src/layouts/MainLayout.vue
src/relay/constructors.js
src/store/index.js
src/store/modules/chats.js

This commit adjusts the save frequency to every 10 seconds. It also
reduces state to a bear minimum of items. Restore will always download
all messages from the remote server at this point. In the future we
shoudl be more intellignet about what data we actually pull on restore.
However, right now we want to ensure that people loading the client
will have a good experience given that they may need to migrate their
schema.

Only save state every 10 seconds

---

src/boot/setup-apis.js
src/utils/constants.js

Currently, we've been using one wallet server. Due to some of the
earlier code around listeners, we got banned. This commit uses a
simply random selection of the main testnet electrum servers to
connect to and set listeners on.

Use a random electrum server for the address listeners

---

src/utils/constants.js

On first run, `cash-testnet.theblains.org` was returning an http 404.  This was causing the application to throw inside the "wallet setup" flow, keeping the "next" button disabled.  I could only proceed by removing the bad server from the list and forcing a reload.

Removing dead server

---

src/components/chat/ChatMessage.vue
src/components/context_menus/ChatMessageMenu.vue
src/components/dialogs/DeleteMessageDialog.vue
src/relay/client.js
src/wallet/index.js

**Motiviation**
Users should be able to delete messages from the remote server, not just locally.
**Implementation**
A dialog box prompts the user whether they'd like to delete.
On confirmation, Stamp will forward the UTXOs attached to this message (if they are unspent) to a change address for safe keeping. It will then proceed to delete using the new DELETE API on the relay server. 
**Notes**
The `forwardTransaction` constructor method is very simplistic and will need to be tweaked in order to preserve privacy. Furthermore, it should be extracted out of the store along with `constructTransaction` in the near future.

Remote deletion

---

.github/pull_request_template.md
LICENSE

It's been a frequent practice that various companies, are whitebox-
relabling open source projects within the open source ecosystem. This
is a large hinderance to the professional maintenance of software
projects. As such, we are changing from an MIT license, to something
which permits the free distribution, and modification of source code
*only*.
We welcome competition within the Stamp ecosystem, and the backend
services and protocol are free and open. However, we wish to force
companies to participate in *this* project, by relicensing or directly
contributing -- rather than producing poorly maintained forks.
My hope is that this project will able to self-sustain through a
commercial offering. Having this project copied and rebranded by for-
profit companies

Update LICENSE and Github pull_request_template

---

src/boot/setup-apis.js
src/router/routes.js

A fair number of electrum servers seem to have bad uptime. This commit
addresses this by trying a new electrum server upon reconnect. Ideally,
we use multiple servers so as to not give away too much information
about which addresses we are using. However, this should work just to
ensure we are able to remain connected to the electrum servers

Ensure we choose a new electrum server on reconnect

---

src/components/dialogs/NewContactDialog.vue

Fixes #70 and also prevents fetching profile data when address is malformed.

Parse address prior to new contact lookup

---

src/components/panels/ContactCard.vue

From the Quasar documentation, it does not seem like `q-img` is meant to
be a container. This commit switches over to using a card container item
instead of `q-img`. `q-avatar` is used later for the actual image.

Use `q-card` instead of `q-img`

---

src/components/chat/ChatList.vue
src/components/chat/ChatListItem.vue
src/layouts/MainLayout.vue
src/pages/Chat.vue

As per title. Fixes up formatting of the various action buttons, and
moves them to the chatlist. Additionally, we fix the use of `q-list`
since the items were being interleaved with the `q-scroll-area` and
should not have been.

Move drawer toggles to a toolbar in the chatlist area

---

src/components/chat/ChatInput.vue
src/pages/Chat.vue

As per title.  Move the attach money button to be clearly visible on
the chat input area.

Add "attach money" icon to chat input area

---

src/components/chat/ChatInput.vue
src/pages/Chat.vue

In order to ensure that users are seeing the stamp amount the are using,
we're adding it to the chat input box. It can also be set from there.

Add stamp amount settings to chat input box

---

src/layouts/MainLayout.vue

We have moved most of the necessary functionality in the contact drawer
to other areas on the screen for relatively small amounts of space. As,
such we don't need to continue showing it constantly by default. This
commit changes the default behavior

Hide contract drawer now that no items are necssary on it

---

src/components/StatusFooter.vue
src/layouts/SetupLayout.vue
src/pages/Setup.vue

Introduces a way to switch between a "basic" and "advanced" setup procedure. The basic setup involves fewer steps. 
In future the basic will should include simplified steps rather than just fewer steps.

Simplify setup

---

src/layouts/MainLayout.vue

Somehow, these references got missed in a previous commit. These are no
longer needed as we maintain a persistent connection to a electrum
server.

Remove references to now deleted `wallet-connect-dialog`

---

src/components/context_menus/ChatMessageMenu.vue
src/components/dialogs/DeleteMessageDialog.vue
src/store/modules/chats.js

Use the `deleteMessage` mutation directly. There is no reason to do
an action within this context.

Remove excess action `deleteMessage` which does not need to dispatch

---

src/store/modules/chats.js

As part of an earlier cleanup, we accidently deleted the readAll
mutation from the chats vuex store. This commit adds it back

Add back mistakenly deleted `readAll` mutation

---

src/components/chat/ChatMessageSection.vue
src/layouts/MainLayout.vue
src/pages/Chat.vue
src/store/index.js
src/store/modules/chats.js

Currently, we're using a hashmap for messages per contact. However,
these should be unordered. It's unclear how these are showing up in the
correct order (beyond the fact that they are added sequentially). In the
future this may change for efficiency purposes, additionally, we want to
be able to omit some parts of `ChatMessage` displays -- as well as add
in separators in some cases. Thus, this commit switches to using a
normal ordered array for each chat's messages.

Use arrays for chat message handling

---

src/components/dialogs/ProfileDialog.vue
src/components/dialogs/SendAddressDialog.vue
src/pages/Setup.vue
src/utils/notifications.js

This commit switches from using a specific error notification function
for each error type, to a generic one. The generic notification should
specialize internally for each error type we can receive in the future.
This allows for moving everything up into the body of one try/catch for
errors while still reporting specific messages.

Change to a generic error notification "toast"

---

quasar.conf.js

During the quasar upgrade, we accidentally changed our build system to
be quasar packager. Unfortunately, packager does not support everything
we need, and seems to error out on MacOS.

Switch back to quasar builder from quasar packager

---

src/router/routes.ts

During the quasar upgrade, we tested using typescript on the router.
However, while this worked in dev mode, eslint complained during build
that we were lacking type annotations. This commit adds them in.

Add type annotations to `router.ts`

---

quasar.conf.js

This reverts a previous change when we bumped the quasar version
that stopped the tray icon from being bundled on MacOS X.

Ensure icons are bundled with the app on MacOS

---

src/components/chat/ChatMessage.vue
src/components/chat/ChatMessageSection.vue
src/pages/Chat.vue
src/relay/client.js
src/store/modules/chats.js
src/utils/relay-client-factory.js

This commit removes headers between messages from the same person in a
particular chat. It also moves the stamp amounts to a tooltip. The
timestamps are shifted to the right. This is the start of a broader
effort to make the chats prettier.

Restyle chat messages for easier reading, consolidated view

---

src/components/chat/ChatMessage.vue
src/pages/Chat.vue
src/utils/constants.js
src/utils/formatting.js

**Motivation**
Suppose a malicious actor copied someones profile and messages you - it would be tough to distinguish the original from the fake purely based on the difference in the address. Especially when one can grind on addresses to achieve similarity.
In order to help users distinguish between the friend and the malicious actor we introduce a colour scheme whereby a colour is selected using `H(address || salt)`.
**Implementation**
The current implementation should work as an basis for future iteration. We currently pick the hue and saturation from the first two bytes of the digest and fix the lightness to achieve a colour from HSL. The lightness is fixed to avoid very bright or very dark colors which make hurt accessibility.
The salt is currently hardcoded into the `constants.js` but …

Basic text coloring

---

src/wallet/index.js

Currently, fixUTXOs takes quite a while for large wallets. While we
need to ultimately store this state locally, this commit makes the
process of updating the validity of these UTXOs be backgrounded. This
makes load times appear to be more snappy.

Time wallet updates, and make fixUTXOs execute in the background

---

src/boot/setup-apis.js
src/layouts/MainLayout.vue

This commit ensure that relay messages are loaded in the background,
and that the wallet is initialized afterwards. This allows for the gui
to be immediately navicable. However, there are many other fixes needed
to ensure that sent messages and other such items work properly.

Make loading occur in the background

---

src/store/index.js
src/store/modules/chats.js
src/store/modules/contacts.js

There were a couple keys that were being saved/restored incorrectly.
Specifically the list of chat participants. Additionally, information
about contacts were not being stored at all. This commit adds that
information back. This ensures tons of "unread" message notifications
do not pop up when the client is restarted.

Ensure proper set of state is maintained to disk and restored

---

src/pages/Chat.vue

Currently, we were only setting bottom if the scroll was *at the bottom*
However, there are times when the chat view is *more* than the
currently loaded number of chats. In this case, bottom was not being
set properly. As a result, scrolling to bottom was not occuring
properly on first load.

Fix issue with chat `bottom` variable not set properly on load

---

src/components/dialogs/ClearHistoryDialog.vue
src/components/dialogs/DeleteChatDialog.vue

**Motivation**
Small typos in the chat removal methods causing calls to fail.

Fix chat removal methods

---

src/boot/setup-apis.js
src/relay/client.js
src/wallet/index.js

This commit ensure wallet init happens on load.  However, it also moves
the UTXO refresh call into the relay client. This ensures that the time
consuming update occurs only when it would be relevant. That is, after
all messages have been loaded and UTXOs that were sent out being
removed.

Ensure wallet init happens on load

---

src/components/chat/ChatList.vue
src/components/chat/ChatListItem.vue
src/layouts/MainLayout.vue
src/pages/Chat.vue

This commit moves the `v-if`s for various components being hidden during
load to be more granular. Ideally, this should be done in a more
holistic way. However, this is a short-term hack for today's release to
ensure that things appear correctly for users.

Make hiding components during load more fine-grained

---

src/relay/client.js
src/store/modules/wallet.js
src/wallet/index.js

Due to a mistake on my part, we were attempting to remove outpoints
which were sent to the recipient of messages. Of course, this won't work
as they are not our outpoints. This commit addresses this by instead
removing outpoints we *used* to generate the stamp/stealth tx.

Fix stamp output removal on message load

---

src/relay/client.js

Due to a previous refactor, message deserialization errors were not
being captured. This commit fixes that mistake.

Fix catching of message deserialization errors

---

src/relay/client.js

Due to a previous update, the client now properly updates its internal
UTXO set state from the relay server. As such, spamming electrum with
significant numbers of `listunspent` requests is no longer necessary.
It is still possible that due to reorgs that we get out of sync.
However, this can be solved by fixing those utxos and re-trying when
we attempt to use them to send a message.

Do not refresh UTXO state for stamps/stealth txns

---

src/components/chat/ChatMessage.vue
src/components/context_menus/ChatMessageMenu.vue
src/components/dialogs/DeleteMessageDialog.vue
src/pages/Chat.vue
src/store/modules/chats.js

During a previous refactor we changed the message list to a simple
array from a map indexed by payloadDigest. This commit adjusts a number
of various props on components to pass through this index. Thus enabling
delete to function properly by updating the array by array index (rather
than attempting to delete a non-existant key).

Fix deletion of messages

---

src/store/modules/chats.js

When first receiving a message from a new contact, the chat is undefin-
ed. As such, the `chats[addr]` is undefined, and it impossible to look
up the `lastRead` field. This commit checks to see if the "chat" exists
and returns zero if not. That prevents this error from being hit.

Fix `Cannot read property lastRead of undefined`

---

src/store/modules/chats.js

In a previous refactor the messages store (per chat) was switched
to an array from an object. However, a few places were missed because
javascript is not typesafe. This commit addresses the problem when a new
contact is added. In the future this should be address more holistically
by moving these files to typescript.

Fix default chat message list to be appropriate type

---

src/components/context_menus/ChatMessageMenu.vue

Remove an extranous call to `sendMessageImpl` when attempting to retry
sending a transaction. Probably an artifact of a failed merge.

Remove extranous retry call for failed messages

---

src-electron/main-process/electron-main.js

In order to stop the app from exiting, we were preventing the default
handler for the `close` event in electron. However, on a mac this makes
it so that the app won't exit on shutdown or a menu shutdown. This
commit updates the main event handlers to check if the app is being
`quit` on MacOS (vs just having the window closed).

Fix exit behavior on mac

---

src-electron/main-process/electron-main.js

Fixes bug by preventing external shell from opening when the developer framework reloads the app.

Fix app reload

---

src/components/chat/ChatList.vue
src/components/chat/ChatListItem.vue
src/layouts/MainLayout.vue

**Motivation**
Being able to switch your chat list to a more compact format allows you to see more of your screen. Currently pulling the chat list too small will result in a ugly mess of text cramped into a small space
**Implementation**
When the chat list is dragged into a sufficiently small column it snaps to a "compact mode" revealing only the display picture and a badge.

Compact sidebar

---

src/components/chat/messages/ChatMessage.vue

This commit fixes an issue where chat messages are reformatted due to
changing number of columns for each message entry when highlighting.

Make sure all columns are always shown even when highlighting

---

src/store/modules/chats.js
src/store/modules/contacts.js

This commit adds a default contact for the current StampChat bot.
It's not great, but it works. This should enable people to discover each
other at large -- hopefully. Iterative improvement.

Add default groupchat contact

---

src/relay/client.js
src/relay/constructors.js
src/wallet/index.js

This commit is the first WIP commit in setting up the wallet to generate
multiple transactions when trying to send another person money. The goal
here is to increase on-chain privacy by not-recombining UTXOs, and by
obfuscating the amounts sent.

Update the wallet to generate multiple transactions

---

src/components/chat/messages/Announcement.vue
src/components/chat/messages/ChatMessage.vue
src/components/chat/messages/ChatMessageReply.vue
src/pages/Chat.vue
src/store/modules/chats.js

Sometimes, a reply message type includes an invalid message digest.
When that occurs, all kinds of rendering errors spew on the console.
This commit addresses those errors by ensuring that undefined data is
properly detected and overridden.

Fix a number of rendering errors caused by undefined data

---

package.json
yarn.lock

Currently, we are persisting everything via vuex-persistance plugin.
However, this plugin stores everything under a single key and as such
is unsuitable for larger data sets, like as is our use case. This
commit adds the leveldb adapter so we can start using leveldb directly.

Add level to our node modules, so we can use it for persisting things

---

src/components/chat/messages/ChatMessage.vue
src/components/dialogs/TransactionDialog.vue

Currently, the rendering of the tabs in this dialog is incorrect. It
does not have the `q-tab-panel` wrapped with the appropriate control,
and sharing a model with the `q-tabs` element. This commit fixes
that issue, as well as adding a type field and renaming the menu item.
The second two changes are because this dialog also shows other types
of outpoints attached to a message.

Fix tab rendering for the transaction dialog and add type info

---

src/adapters/vuex-relay-adapter.js
src/layouts/MainLayout.vue
src/relay/client.js
src/router/routes.ts
src/store/index.js
src/store/modules/chats.js
src/store/modules/contacts.js

We need to persist valid UTXOs to disk, as a future commit will be
removing the re-processing of messages upon load. This commit enables
use of async calls from the Vuex plugin that will be used in the future
to interact with leveldb.

Start saving wallet UTXOs to disk

---

src/pages/Chat.vue
src/store/modules/contacts.js

As per title. This simplifies some APIs and generally makes it easier
to avoid `undefined` results.

Remove name color generation from Vuex store. Generate on fly

---

src/components/chat/ChatList.vue
src/components/chat/ChatListItem.vue
src/components/chat/messages/ChatMessage.vue
src/components/chat/messages/ChatMessageReply.vue
src/relay/client.js
src/store/modules/chats.js
src/store/modules/contacts.js

Due to the way messages are sent to the client, they may have various
malformations in them. The client as such, needs to be robust to invalid
messages. This commit adds more checks for undefined values that cause
exceptions in JavaScript. These particular spots have been observed in
practice when for whatever reason, some entries are removed from the
keyserver.

Clean up various places where undefined is not checked

---

src/adapters/level-message-store.ts
src/adapters/vuex-relay-adapter.js
src/layouts/MainLayout.vue
src/relay/client.js
src/relay/storage/level-storage.ts
src/relay/storage/storage.ts
src/store/index.js
src/store/modules/chats.js
src/types/bitcore-lib-cash/bitcore-lib-cash.d.ts
src/types/level/level.d.ts
src/utils/constants.js

Previously, we used the Vuex-persistence store for messages. However,
this uses a single localstorage key for storing all data as one
serialized JSON blob. The limitations of this caused undefined behavior
after a certain amount of messages were received. Thus, we are switching
to manual storage against leveldb/indexdb. This wrapper allows us to
implement once, and have support in both node and electron/browsers.
Node support is important as we also want to use these as libraries in
the future to enable people to write bots and other headless wallets.

Use level storage wrapper for saving messages 

---

src/boot/setup-apis.js
src/layouts/MainLayout.vue
src/pages/Setup.vue
src/utils/constants.js

The electrum-cash `client.connect` method never resolves its promise
when connections fail. Thus the setup prior to MainLayout loading was
never succeeding if the first attempted Electrum server was offline.
This commit removes the `await` and updates downstream logic to properly
handle the need to reconnect to the electrum server immediately at
startup.

Address issues with reconnect logic on load

---

src/store/modules/chats.js

Ensure last read time is updated when sending a message. This ensures
that when reloading from disk that the last few outbound messages do
not show up as unread.

Ensure sending message updates read time

---

src/boot/setup-apis.js
src/router/routes.ts
src/store/modules/chats.js

Due to the previous conversation to leveldb for storing messages, some
other problems were introduced upon loading. These center around the
store possibly not being fully loaded before launching other components.
This commit either ensures certain initalization steps only happen after
the electrum client, and the store, are fully loaded.

Fix race conditions introduced when enabling async store

---

src/adapters/level-outpoint-store.ts
src/boot/setup-apis.js
src/components/chat/ChatList.vue
src/components/context_menus/ChatMessageMenu.vue
src/components/dialogs/SendAddressDialog.vue
src/components/dialogs/WalletDialog.vue
src/components/setup/DepositStep.vue
src/pages/Setup.vue
src/pop/index.js
src/relay/client.js
src/relay/constructors.js
src/store/index.js
src/store/modules/wallet.js
src/wallet/helpers.js
src/wallet/index.js
src/wallet/storage/level-storage.ts
src/wallet/storage/storage.ts

In order to further enable headless bots, we need to move away from Vuex
for anything that is non-GUI. This commit adds an outpoint store for
the wallet that uses leveldb directly instead of Vuex-persistence.

Move UTXO storage to leveldb

---

src/boot/setup-apis.js
src/layouts/MainLayout.vue
src/wallet/index.js

1. Retry of calling wallet refresh did not properly terminate
when `setTimeout` was called.
2. Due to multiple events being fired on close, sometimes a new
connection would be started before the last close event on the
electrum client. This commit ensures that the connected observable
is only set once, so that the UI is consistent with the connection
state.

Fix more reconnect issues in the wallet

---

src/components/dialogs/SettingsDialog.vue

**Motivation**
Prior to this the settings dialog would switch width based on which tab was open.

Fix settings dialog width

---

src/boot/setup-apis.js
src/components/dialogs/SendAddressDialog.vue
src/layouts/MainLayout.vue
src/pages/Setup.vue
src/relay/client.js
src/wallet/index.js

Currently, we set the electrumClient field in a variety of places once
as soon as the client has been created. However, this means that we may
attempt to make requests before connection is completed. This commit
changes the system to provide a promise to a client, which gets resolved
or rejected, when the client has actually connected. This ensures that
the client is ready before making requests, and that init() is
properly called in the wallet every time the electrumClient is restarted

Replace electrumClient with a promise to a client

---

package.json
src-electron/main-process/electron-main.js
src/layouts/MainLayout.vue
yarn.lock

This commit adds the electron-windows-badge package in an attempt to
support badge icons on windows. This does not fix Tray icons under
MacOS, or linux, unfortunately.

Attempt to add windows badge icons

---

src/pages/Setup.vue

**Motivation**
Previously the reactivity triggered only on `$electrum.connected` changes, this worked to prevent progression through setup when the electrum connection went down but didn't react to any of the inner computed properties changed e.g. `this.isWalletValid`.
We fix this by computing a `forwardEnabled` property which aggregates all the requirements reactively in a boolean expression allowing the user to progress only when required.

Fix setup validation

---

src/wallet/index.js

Currently, we are not properly awaiting freezeUTXO which would hyptoth-
etically allow a frozen UTXO to be selected again before it froze.
Additionally, constructTransaction was not properly filtering out frozen
UTXOs from construction. This meant that early on in the setup process
(and possibly ather places) you could not generate two of the same
output-size transactions back-to-back before the wallet was updated from
the electrum subscriptions.

Ensure constructTransaction[Set] does not reuse UTXOs

---

src-electron/main-process/electron-main.js

This variable needs to be able to be set, even if it is unused. It hangs
around and receives events in the rendering thread for updating the
window badge overlays.

Fix lit error around unused variable

---

src-electron/main-process/electron-main.js

**Motivation**
Removal of the `nativeIcon` from the `browserWindow` caused linux dock icon disappear.

Fix dock icon on Linux

---

src/components/panels/ContactPanel.vue
src/pages/Chat.vue

**Motivation**
Many dialogs were previously marked as `persistent`, preventing them from being exited via the escape key.
Fixes https://github.com/cashweb/stamp/issues/235

Remove persistence from dialogs

---

src/components/contacts/ContactList.vue
src/components/dialogs/ContactBookDialog.vue
src/layouts/MainLayout.vue
src/store/modules/contacts.js

A previous commit enabled the contact search dialog to be opened with
Cmd-K. However, there were some oddities in the behavior when pressing
enter, or having accidentally had an address which was not part of the
search results. This commit removes some complexity, and adds the
necessary watchers to make sure that the address is always defined.
Fixes #221, #225, #287

Fix keyboard navigation of contacts

---

src/relay/client.js

Due to the way we are now serializing and de-serializing addresses, we
need to ensure we do not depend on Bitcore types directly. This commit
fixes the one place where we were still serializing Bitcore Address
objects and stringifies it into a Base58 address. This ensures that
the UTXOs can be used later without rehydrating.

Fix serialization format of BCH Addresses

---

src/components/contacts/ContactList.vue

Currently, each time the contact search dialog is opened, a keydown
listener is registered, but never unregistered. This causes various
actions to fire later when entering messages into the chat input.
Generally, it is unnoticed, but it can cause strange issues where the
active chat switches after pressing enter. This commit ensures the event
handlers are unregistered when the dialog is closed.

Ensure event listener in contact dialog is unregistered

---

src/wallet/index.js
src/wallet/lock.js

Since we added leveldb support for storing UTXOs, constructTransanction*
is no longer synchronous. This means multiple transactions can be
constructed at the same time, possibly attempting to use the same UTXOs.
As a result, things which send transactions quickly (like bots) are
rather broken. This commit addresses that issue by adding a simple
lock around the construct transaction function. Future work should make
this more clean upstream.

Ensure only one transaction is being constructed at a time

---

src/adapters/level-outpoint-store.ts
src/wallet/storage/level-storage.ts

Leveldb does various checks and cleaning when it is opened and closed.
This creates unnecessary overhead every time we want to get or set a
key. As such, this slows transaction generation considerably. This
commit removes that process and ensures the db is gracefully closed when
possible.
Part of fixing #298

Do not open/close leveldb repeatedly

---

src/adapters/level-message-store.ts
src/relay/storage/level-storage.ts

As with the UTXO database, we don't want to be opening and closing the
message database constantly as that voids the in memory cache and
causes compactification. This commit makes it so this database is
kept open.

Open message database only once

---

src/store/index.js

This log line was added for debugging previously, but is no longer
necessarily and generally just makes a lot of spam in the console.

Remove unnecessary log line

---

src/components/dialogs/SendAddressDialog.vue
src/relay/client.js
src/wallet/index.js
src/wallet/storage/level-storage.ts

Currently, our outpoint iterators erroneously include frozen UTXOs. This
commit removes them from being returned by the iterators, and ensures
that they are eventually fixed/deleted.

Fix frozen outpoint iterators

---

src/wallet/index.js

We need an index to use `Array.prototype.splice` with. Currently, we're
using `find`. This commit fixes it via `findIndex`. Yay typeless
languages.

Use the appropriate search function in javascript

---

src/utils/constants.js

This electrum server does not drop connections, but insteads holds them
open despite doing nothing. This breaks the reconnect logic and also
prevents any messages from being sent.

Remove unreliable electrum server

---

src/wallet/storage/storage.ts

This should have been an issue sooner, but we're only using these type-
script classes from within TypeScript at the moment.

Fix the wallet storage class type

---

src/wallet/index.js

Because we now split transaction bundles into a set number of fragments,
it is better to now try to use a random UTXO that is bigger than
whatever amount was determined to be used. This ensures we don't try
to create 1-input -> 1-output transactions for no particular reason.
Doing so would waste users funds on fees.

Ensure we attempt to use sufficiently sized UTXOs first

---

src/wallet/index.js

Currently, the indented recipient, and change, are always output 0 and 1
respectively. This commit enables swapping the location randomly and
properly packing that information into the Stamp payload.

Enable change output order shuffling

---

src/relay/storage/level-storage.ts
src/types/level/level.d.ts
src/wallet/storage/level-storage.ts

Based on information provided from from Jason Dreyzehner, we're updating
the TS declaration for level. This makes things a bit cleaner when
using the level module in typescript.

Improve `level` module TypeScript definitions

---

src/components/chat/ChatInput.vue

I thought this looks a little better

increase stamp price input width, add price

---

src/components/Profile.vue
src/components/Settings.vue
src/components/chat/ChatInput.vue
src/components/chat/ChatList.vue
src/components/contacts/ContactItem.vue
src/components/dialogs/ContactBookDialog.vue
src/components/dialogs/NewContactDialog.vue
src/components/dialogs/ReceiveBitcoinDialog.vue
src/components/dialogs/SendAddressDialog.vue
src/components/panels/SettingsPanel.vue
src/i18n/en-us/index.ts
src/pages/Chat.vue
src/pages/Setup.vue
src/utils/constants.js

Thank you for contributing to Stamp! We really appreciate it. Our mission is to spread P2P electronic cash to the world. 
Please note, due to common industry practices of re-packaging open source software by for-profit business, we have an unusual software license. This license provides open access to the software source code, and reproduction thereof by community (non-commercial) projects, but excludes use of reproductions, and repackaging, by other for-profit organizations.
As such, by opening this pull request you acknowledge that you are providing the owners of this project an unlimited license to use and reproduce your contribution.

add english language support

---

src/components/chat/ChatListItem.vue

Mistakenly, we set the valueUnread prop to be of type number. However,
it is passed in as a formatted balance already. This is causing
validation errors in the console. This commit adjusts the expected
prop type.

Fix prop type error in ChatListItem

---

src/adapters/level-outpoint-store.ts
src/boot/setup-apis.js
src/store/modules/wallet.js
src/wallet/index.js
src/wallet/storage/level-storage.ts
src/wallet/storage/storage.ts

Currently, using async functions to interact with UTXO selection means
that the event loop runs in between every UTXO load. This commit
obviates that by keeping an in memory cache of all UTXOs, and updating
the on-disk storage asynchronously.

Make UTXO storage API synchronous, move disk updates to background

---

src/components/dialogs/ProfileDialog.vue
src/keyserver/handler.js
src/layouts/MainLayout.vue
src/pages/Setup.vue
src/relay/client.js

Currently, we only ever upload our profile, or keyserver metadata when
going through the setup. This means that if for some reason we change
backends our client will not automatically update keyserver/relay server
data.

Ensure profile is setup with keyservers and relay servers on startup

---

src/components/dialogs/SendBitcoinDialog.vue

Mistaken property type was generating errors on the javascript console.
This fixes the type restriction.

Fix property type on SendBitcoinDialog component

---

src/wallet/index.js

Some update to the electrum client removed the `events` field and
instead directly inherited from the event emitter class. This means
we need to call `.on` directly rather than against the `events` field.
This commit fixes the bug this introduced.

Fix event listeners in electrum client

---

package.json
src/boot/setup-apis.js
src/utils/constants.js
src/wallet/index.js
yarn.lock

Use the latest fulcrum cash version that supports websockets. This will
allow us to run Stamp in a web browser or with capacitor on mobile
devices. This new version also fixes several bugs.

Use latest electrum-cash client which supports websockets

---

package.json
src/relay/client.js
yarn.lock

This will allow connecting from both Electron and from Capacitor, and
web browsers in general. This will greatly improve our ability to
support other platforms. However, we also need to update the relay
server to support the full bearer token specification. The web browser
API for websockets does not allow setting headers, which means the
bearer token cannot be included in the Authorization header when
negotiating a websocket.

Use isomorphic websocket module for connecting to relay server

---

src-electron/main-process/electron-main.js

Disabling this was unnecessary, and a red herring from when the relay
server was responding with 502s. These errors cause the JavaScript
http connection library to sometimes complain about CORS problems.

Re-enable CORS checks in Electron

---

src/boot/setup-apis.js
src/wallet/index.js

Some automatic re-subscribing and other functionality was added to the
latest version of the client. This caused some issues with the internal
disconnect handling logic we implemented. We may be able to get rid of
that logic in the future, but for now minor adjustments are made to
fix this particular issue.

More fixes with the use of the newer electrum client

---

src/boot/setup-apis.js
src/components/setup/SeedStep.vue
src/pages/Setup.vue

Due to state errors around how seeds are generated and stored during
setup, the setup could not be resumed if the xpriv had been generated,
but the setup not completed. This commit addresses those issues in order
to ensure that funds are not lost during a partial setup.
However, from the areas touched, it should be apparent that the way in
which this state is being handled is rather tangled. There needs to be
an overarching concept for "setup complete" rather than it being
inferred from various other variables being set.
Fixes #338

Ensure generated seed phrases are always saved, and setup can be resumed

---

src/pages/Setup.vue
src/wallet/index.js

Not reseting leveldb caused  the balance to not properly refresh due to
the desync between the rehydrated wallet being reset, but not the
leveldb store when the setup regenerates a new wallet.
Thus, we need to clear out the actual wallet at the same time. In the
cuture we should remove explicit UTXO tracking in the Vuex store, and
instead only update the balances as UTXOs are deleted/removed.

Ensure UTXOs are cleared from leveldb during Setup

---

quasar.conf.js

Currently, on iOS the toolbars clobber part of the screen. This should
address that problem.

Ensure capacitor adds toolbar space

---

src/relay/client.js

The rest of the code expects arraybuffers. But the default is Blobs
for the browser websocket API. This tells it to use array buffers
instead.

Fix Websockets to use Arraybuffers instead of Blobs

---

package.json
src/relay/constructors.js
src/relay/crypto.js
src/store/modules/chats.js
src/wallet/index.js
yarn.lock

These only happened to work in node. They do not work in the browser.
This commit properly converts them to buffers before passing them
through to bitcore.

Fix buffer types being passed into bitcore lib

---

package.json
yarn.lock

Capacitor comes with a number of plugins we will need to run in the
browser/mobile. Similar to some of the electron-specific APIs. We will
polyfill the specific items we use in the future.

Add capacitor as a dependency so we can special case for mobile

---

src/adapters/level-message-store.ts
src/adapters/level-outpoint-store.ts
src/adapters/vuex-relay-adapter.js
src/boot/setup-apis.js
src/pages/Setup.vue
src/store/modules/contacts.js
src/store/modules/wallet.js

Level module is synchronouse in electron/node, however in the browser
it uses IndexDB. This requires that everything downstream be async.
However, we need to switch away from IndexDB entirely, as there is
eviction policies on mobile that we may run into.

Make message store async so it can be used with IndexDB in browser

---

src/utils/constants.js

Previously, all the other BCHA testnet servers were down. However, we
are now running our own. So, use that testnet server instead.

Ensure we are using testnet fulcrum servers

---

src/components/chat/ChatList.vue
src/components/panels/LeftDrawer.vue
src/components/panels/SettingsPanel.vue
src/layouts/MainLayout.vue
src/pages/Chat.vue

We had originally moved the chat list out of the drawer because it was
not resizable there, and looked bad on desktop. However, putting it
there works well for mobile for the time being, as we want to get to
an MVP position for mobile first.

Move chat list to drawer for better mobile support

---

.eslintrc.js
src/boot/i18n.ts
src/components/panels/SettingsPanel.vue
tsconfig.json
yarn.lock

TSLint has been running out of memory due to trying to lint files
which are not appropriately part of the project. This commit updates
the configuration and fixes a few lint errors that were hanging
around as a result of being unable to build.

Fix tslint configuration issues preventing build

---

src/layouts/MainLayout.vue

Currently, the drawer does not open the first time the client is loaded
due to the active chat address not being set. This means on desktop you
can never get to the drawer due to the heading bar not being shown. This
commit introduces a temporary fix of showing the drawer on load. A
better fix would be introducing a news page for people to land on.

Ensure drawer opens on first import

---

src/components/setup/AccountStep.vue
src/i18n/en-us/index.ts

The import button was incorrectly wired up to hide the import field
and never show it again. This was incorrect behavior, and is fixed in
this commit.

Fix import flow in account step (was not toggling)

---

src/relay/client.js
src/relay/extension.js
src/wallet/index.js

During past refactors, a few issues with delete message and other
parts of the codebase were broken. THis commit fixes the issues around
forwarding deleted UTXOs and an accidental inversion of conditions when
receiving a message with a payload digest instead of a full message.

Fix several type issues with delete message that had occured

---

quasar.conf.js
src/boot/network-prefix.ts
src/components/dialogs/NewContactDialog.vue
src/components/dialogs/ReceiveBitcoinDialog.vue
src/components/dialogs/RelayConnectDialog.vue
src/components/dialogs/SendAddressDialog.vue
src/components/dialogs/TransactionDialog.vue
src/components/panels/ContactCard.vue
src/components/panels/ContactPanel.vue
src/components/setup/DepositStep.vue
src/keyserver/handler.js
src/relay/client.js
src/relay/crypto.js
src/utils/constants.js
src/wallet/index.js

Currently, Bitcoin ABC is still using the `bitcoincash` address prefix.
However, this is not a long term situation. Additionally, our codebase
hardcodes the network name in many different places. This commit splits
the display of addresses, and the use of the addresses in the API
backend -- and uses one constant everywhere so it'll be easy to swap
out.

Switch codebase to use parameterized network names for display vs API

---

src/i18n/en-us/index.ts
src/keyserver/handler.js
src/pages/Setup.vue

When a person signs up, they need to make two payments immediately.
One for the keyserver, and one for the relay server. However, if they
only have one UTXO, this won't be possible until the change of the first
transaction settles. This commit updates the error handling around the
second payment to retry until there are funds in the wallet due to
the subscriptions from the first transaction being hit.

Ensure signups for *BRAND NEW* accounts don't fail

---

README.md

Issue: The safari inspector keeps crashing when remote debugging with real iOS device.
Root cause: The inspector crashes when any file is too large (not sure the limit)
Reference: https://stackoverflow.com/questions/31251938/safari-web-inspector-keeps-disconnecting
Solution: Should change the "devtools" option in quasar.conf.js file from 'source-map' to others, such as 'eval-source-map'

Update doc to able to remote debugging ios device with Safari inspector

---

.vscode/settings.json

As per title. These had been excluded from the repo, but should have
been included so other developers use the same lint settings as
expected by the quasar build process.

Add standard VS Code linter settings to repo to ensure consistency

---

src/cashweb/keyserver/handler.ts
src/components/agora/AgoraMessage.vue
src/store/modules/agora.ts

This commit adds voting support to the Agora. The UX is currently adding
10 XPI per vote or downvote, and they are delayed so that only one
transaction is sent per set of clicks provided they all happen within 1
second of the first click.

Add basic vote support

---

src/cashweb/keyserver/handler.ts

Currently, if a payload is absent from an entry, protobufs returns an
empty string. This trips an assertion that was added to make typescript
happy and prevents the Agora page from loading if such a message exists.
Somehow someone posted such a blank message to the server. Possibly due
to an unknown bug, or someone is playing with the source.

Ensure message entries without a payload are ignored

---

src/store/modules/agora.ts

When clicking into a post, it will attempt to fetch the specific
message. In this case, all messages are reprocessed and added to the
replies of the parent. This is resulting in GUI glitches where replies
are showing up multiple times under a parent post.

Don't re-insert replies on parent messages when saving a single message

---

src/components/agora/AgoraMessage.vue

This is a temporary fix for this problem. Ideally, the client would
attempt to download the parent where relevant. It is hard to follow a
conversation if this doesn't happen.

Fix blowing up when posts reference parent posts which are unknown

---

src/router/index.ts

Unregistered users could not navigate into replies, or be linked to
specific messages. This commit allows the any subpath of an allow route
past the signup route guard.

Allow deeplinking to specific Agora posts for unregistered users

---

src/pages/CreatePost.vue

The validation of posts incorrectly assumes that the URL will always
have a length. However, by default this field is set to null. This
commit simply shortcuts validation when that is the situation.

Fix validation of URLs on CreatePost

---

src/components/agora/AgoraMessage.vue
src/components/agora/AgoraMessageReplies.vue
src/layouts/AgoraLayout.vue
src/pages/Agora.vue
src/pages/AgoraPost.vue
src/router/routes.ts

Currently, the Post Page and the main agora page do not share layouts.
This commit refactors the content to share a layout and use a nested
router-view in order to ensure both pages are rendered in the same way.
Additionally, we add v-bind="$attrs" in order to allow events on message
to propagate all the way back up to the router-view and layout.

Refactor the Agora to use router views to dedupe layout

---

src/pages/Agora.vue
src/store/modules/agora.ts

A previous commit changed the behavior of the Agora fetching routine to
only fetch recent messages. However, this resulted in filtering behavior
not to function correctly as it was processing on the server side. This
commit moves the filtering to the client side and uses v-show instead of
filtering server side so that messages can remain cached locally.

Fix message filtering in Agora main page

---

src/components/agora/AgoraMessage.vue
src/layouts/AgoraLayout.vue
src/router/routes.ts

Moving the create post page under the Agora subpath. This enables it to
use the same layout as the rest of the agora for consistency.

Move create post route under Agora subpath

---

src/store/modules/agora.ts

While changing the message download to only fetch new messages, we
inadvertantly got rid of the code to blow out existing replies before
they were reindexed. This code should be optimized to only process new
messages.

Once again fix message store not to duplicate replies

---

src/components/forum/ForumMessage.vue
src/store/modules/forum.ts

Due to processing messages while they are part of the state the DOM was
attempting to update at the same time. This caused lots of DOM mutations
and redraws which slows down the loadtimes for forum pages
significantly. This commit mutates the lists outside of the DOM updates,
and then sets the whole message state at once.

Fix message load times in forum

---

src/cashweb/keyserver/handler.ts
src/store/modules/forum.ts

When posting or voting on a message, the message or update to votes are
not currently displaying due to the way that caching messages on reload
was setup. This commit forcibly reloads messages which were voted on or
posted.

Fix message updates on votes/posts

---

src/cashweb/relay/index.ts
src/store/modules/chats.ts

When converting over to typescript, it turns out that p2pkh sends do not
work unless you have yourself added as a contact. This will not be the
case for most people. This commit addresses the issue by
short-circuiting the chat message addition and only adds the message to
the overall index for later cache checks and deletions.

Fix p2pkh sends

---

src/store/modules/forum.ts

Due to some typos, the wrong lists were being amended and sorted when
attaching replies to their parent messages. This commit fixes those two
issues by correctly indexing the temporary list of messages.

Fix reply attachment to parent messages

---

src-capacitor/android/app/build.gradle
src-capacitor/android/app/src/main/AndroidManifest.xml
src-capacitor/android/variables.gradle

SDK version, Stamp version number, and removing a few unrequested
permissions were required to apply for a Google Play store listing.

Update Android manifests for Google Play

---

src/components/forum/ForumMessage.vue

Move timestamp to far right as it is variable width. Also, use moment
calendar formatting so that times are easier to read at a glance.

Change formatting of timestamps in forum

---

src/components/panels/ForumDrawer.vue
src/layouts/ForumLayout.vue
src/pages/CreatePost.vue
src/pages/Forum.vue

By using a right drawer for these items we open up some more room
and the potential to add more configuration to how things are displayed
in the future. Currently, the display here kind of stinks, but we
can re-theme things more in the future in an iterative fashion.

Move header buttons to side panel of Forum

---

src/router/index.ts

During the re-org of the routes, creation of a post became "unprotected"
but it actually does require an account. This commit ensures that users
who are not yet signed up are redirected to the sign up page.

Protect `/forum/new-post` route for non-signed up users

---

src/components/forum/ForumMessage.vue
src/pages/Forum.vue

Apparently, `router-view` does not pass through it's listeners via
`$attrs` like the docs say. However, it does work when manually
re-emitting events. Very odd, but this commit fixes the issue.

Fix topic filtering button on Forum

---

src/pages/CreatePost.vue
src/pages/Forum.vue
src/store/modules/forum.ts

The Forum page was not reloading after a post due to the filter within
the computer property. It caused it not to detect that the computed prop
was dependent on the underlying array length. This adds a toast, and
fixes the reload, so that users don't post multiple times thinking their
post did not go through.

Add toast on post, and ensure it loads

---

src/cashweb/keyserver/handler.ts
src/pages/CreatePost.vue

If a message fails to send for whatever reason, we need to fix our UTXO
set that was frozen and display the error to the user. Ultimately,
this should be wrapped with user-friendly error messages, but for the
purpose of bug reports, leave them displaying all information.

Add error notification to Create Post screen

---

src/components/Profile.vue
src/components/panels/ContactCard.vue
src/i18n/en-us/index.ts
src/pages/AddContact.vue

This was added for a demo of the app, and people keep getting confused
by it. So, remove it for now until there is some support for
notification thresholds and configuration thereof.

Remove mentions of minimum acceptance price

---

src/components/panels/ForumDrawer.vue
src/pages/Forum.vue

Seemed to be working due to default threshold being 0, but it actually
was not being properly parsed as a number when input. Additionally,
the filter was multiplying the post value by 1 million, rather than
the selected threshold.

Fix Threshold filtering on Forum

---

src/components/forum/ForumMessage.vue
src/components/panels/ForumDrawer.vue
src/pages/Forum.vue
src/store/modules/forum.ts

Currently, this setting just disables showing post bodies; but in
the future it could be changed to allow a totally different view
of Forum posts when in compact mode.

Enable configuration for a "compact mode"

---

src/pages/CreatePost.vue
src/store/modules/forum.ts

@schancel : 
"People are entering lots of random topics and sometimes mistyping
existing ones. This commit switches the topic input on the CreatePost
screen to be a QSelect with all the known topics available. It also
allows for manually specifying a new topic, however it is preferable
to keep posts within known topics."
This is same code/branch as https://github.com/StampChat/stamp/pull/469
There were some conflicts with that branch so I made a new one from current master.
There was a bug in that branch where after user created a post and came back there was no topics available. Not sure if it was caching error or some new commits to master fixed it, but it works fine now.
Adding new topic works with clicking on it or pushing enter or tab. 
It doesn't work when you just type it and click …

Give topic hints to user when posting

---

package.json
src-electron/electron-main.js
src-electron/electron-preload.js
src/layouts/MainLayout.vue
yarn.lock

Custom toolbar makes stamp for desktop look more elegant. 
New package is added to the project via `yarn add @electron/remote`
based on -> https://quasar.dev/quasar-cli/developing-electron-apps/frameless-electron-window#minimize-maximize-and-close-app
Minimize, maximize, close and move around work as expected.
Not showing on other platforms via "electron-only" class.

Toolbar for electron build.

---

src/pages/Forum.vue

There is short period of time where user opens an app and forum is still loading posts. 
Temporary solution is to add a spinner in this place. 
Different spinner can be picked here -> https://quasar.dev/vue-components/spinners#example--other-spinners
Spinner color and size can be customized.
Current one is:
https://user-images.githubusercontent.com/11517372/142004504-2ea9c48b-107d-42b9-93a4-23585cffe495.mp4

Add spinner at forum page before posts are loaded.

---

src/cashweb/keyserver/handler.ts
src/cashweb/relay/index.ts
src/cashweb/wallet/index.ts

Currently, this is done through a potentially expensive `listunspent` call to Electrum. Chronik gives us the state of a list of UTXOs directly with a single call, which is much faster.

Check UTXOs with Chronik Indexer's `validateUtxos`

---

src/cashweb/relay/index.ts
src/cashweb/wallet/index.ts

Currently, we use Electrum to broadcast txs. However, this apparently sometimes silently drops txs, and it also doesn't verify that the transaction doesn't burn SLP tokens.
Using Chronik, this is no longer a problem.

Use Chronik Indexer to broadcast txs

---

src/adapters/vuex-relay-adapter.js
src/boot/setup-apis.ts
src/cashweb/relay/index.ts
src/components/StatusFooter.vue
src/components/panels/LeftDrawer.vue
src/layouts/MainLayout.vue
src/pages/Setup.vue
src/types/vue.d.ts

Makes the code independent of used indexer. Currently, `$electrum` only has a `connected` field.

Rename `$electrum` Vue observable to `$indexer`

---

package.json
src/boot/setup-apis.ts
src/types/vue.d.ts
src/utils/constants.ts
yarn.lock

All instances where an Electrum client is required have been replaced by Chronik, therefore we can remove all occurances of Electrum from the codebase now.

Remove Electrum from codebase

---

src/utils/notifications.ts

Disable notification timeouts and handlers in electron so as to allow
the OS configuration to properly manage notifications.

Allow OS to manage notifications

---

.vscode/settings.json

Stop VS Code from saving files in a way which will cause the prettier
CI checks to fail.

Make VS Code format settings match prettier expectations

---

src-electron/electron-main.js
src-electron/electron-preload.js
src/layouts/MainLayout.vue

The recently added custom titlebar does not properly render on MacOS.
This commit reverts those changes to restore native OS titlebars.

Remove custom titlebar setup

---

src/adapters/vuex-relay-adapter.js
src/cashweb/relay/index.ts
src/cashweb/relay/pAll.ts
src/layouts/MainLayout.vue
src/store/modules/chats.ts

Currently, the receiving of messages updates the GUI after every message
is received. This really provides a bad experience for the users. This
commit is a pack of changes to bulk load messages initially to avoid
updating the DOM after each message.

Improve initial sync speed by only committing received messages in bulk

---

src/pages/AddContact.vue
src/router/index.ts
src/store/modules/contacts.ts

Move contact fetching logic to the contacts store so that it can
check to see if a contact already exists. Additionally, don't try to
set the active chat if the contact already exists. This caused
loops due when changing routes quickly in some cases where the
active chat will bounce around between the contacts which were clicked
quickly in the chat list.

Don't redownload contacts on route change

---

src/cashweb/relay/decode-entry.ts
src/cashweb/relay/encode-entry.ts
src/cashweb/relay/index.ts
src/cashweb/types/user-interface.ts
src/store/modules/chats.ts

In order to implement message forwarding, we need to be able to
recursively encode message entries. This requires the functions for
encoding and decoding entries, to be have their own names so they can be
recursively called. This commit refactors those portions of the relay
client to be their own functions to enable this future functionality.

Refactor message item encoding and decoding to be their own functions

---

src/layouts/MainLayout.vue

Safari for iOS does not support the new promise version of
`Notification.requestPermission`. This code catches the undefined error
that results on Safari iOS and uses the callback based version of
requestPermission in that case.

Fix iOS loading by using callbacks with `Notification.requestPermission`

---

src/boot/setup-apis.ts
src/stores/contacts.ts

1. `ce3c4cf`: Work around a bug in which the `profile.pubKey` Uint8Array is incorrectly saved/restored as an object
2. `8d7f75d`: Ensure the contact store is loaded at boot in the setup-apis
3. `cf6a2d6`: Accomplishes the same as `ce3c4cf`, except it saves the `profile.pubKey` as a binary string using `JSON.stringify` replacer function. The binary string is restored as a Uint8Array in the `JSON.parse` reviver function, which is then passed to the `rehydrateContacts()` and properly converted back into a `PublicKey`

contactStore fixes

---

src/stores/wallet.ts

During setup, navigating back and forth can cause the balance to keep
incrementing due to it rescanning, dropping the UTXOs, but not resetting
the balance.

Ensure balance resets when wallet is reset

---

src/components/setup/AccountStep.vue
src/pages/Setup.vue
src/stores/wallet.ts

Currently, users are losing funds due to clicking back after funding
their first wallet. This is because the seed regenerates and isn't
saved in the store.
This commit ensures the seed is generated on Setup load only if it does
not exist. Seeds on the "new character" page are also not regenerated on
load. And the wallet restore function now maintains the seed even when
the xpubkey is not yet generated.

Ensure seed is saved permanently and not regenerated before setup

---

src/pages/Forum.vue

This was one of the earlier pages to be converted to pinia, and we
missed creating refs for the store getters.

Fix reactivity on Forum page after Pinia updates

---

package.json
yarn.lock

Latest OS X no longer works with the existing version of
electron-builder. This bumps the version to fix that.

Update electron builder to latest version to fix issue on new OS X

---

src/components/dialogs/ContactBookDialog.vue
src/pages/AddContact.vue
src/stores/chats.ts
src/stores/contacts.ts

This commit fixes several issues around adding new contacts that didn't
seem to cause issues when using Vuex (although it should have). There
are several issues fixed: Handling undefined values in AddContact.vue,
marking contact PubKey's raw everywhere relevant, and also ensuring
that the chat is created when a new contact is added. The chat list side
bar requires a chat to be created, in addition to the contact being
added.

Fix adding new contacts and various pubkey handling associated

---

src/components/forum/ForumMessage.vue
src/components/panels/ForumDrawer.vue
src/layouts/ForumLayout.vue
src/pages/CreatePost.vue
src/pages/Forum.vue
src/stores/forum.ts
src/utils/sorting.ts

Currently, the posts were not being filtered by the selected duration.
This commit should make only recent messages show up in the Forum main
view.
Closes  #574

Update Forum time-based filtering

---

src/cashweb/relay/decode-entry.ts

During receipt of a stealth lotus send, the relay client was incorrectly
adding the stealth outgoing utxos to the local wallet. This would bust
sends by attempting to include those UTXOs in the inputs of a new
transaction. This commit adds back the missing "continue" which short
circuits the wallet add for outbound transactions.

Fix stealth transaction sends

---

src/layouts/ChatLayout.vue
src/layouts/ForumLayout.vue
src/layouts/MainLayout.vue
src/layouts/SetupLayout.vue
src/layouts/TopicLayout.vue
src/pages/AddContact.vue
src/pages/AddTopic.vue
src/pages/Changelog.vue
src/pages/Chat.vue
src/pages/CreatePost.vue
src/pages/Profile.vue
src/pages/Receive.vue
src/pages/Send.vue
src/pages/Settings.vue
src/pages/Setup.vue
src/pages/WipeWallet.vue

Previously we used nested QLayouts early on in development because we
didn't understand out nested RouterViews worked. These "container"
versions of QLayout come with a lot of problems that caused rendering
issues. This commit removes them and adjusts where QPageContainer and
QPage are placed so that the nested layouts are no longer necessary.
This should speed up rendering, and hopefully fix the weird keyboard
issue on mobile.

Remove nested QLayouts

---

src/components/chat/ChatList.vue
src/components/panels/ChatRightDrawer.vue
src/components/panels/LeftDrawer.vue
src/components/panels/SettingsPanel.vue
src/layouts/MainLayout.vue
src/pages/AddContact.vue
src/router/index.ts
src/stores/chats.ts
src/stores/contacts.ts
src/utils/routes.ts

Update activeChatAddr from within the router, and ensure it is set to
null when the current route is no longer a chat. This fixes a bug where
in some cases a non-chat route was selected and the user would not be
able to navigate back to the appropriate user due to `acitveChatAddr`
still being set to that contact.

Fix bug around updating the stored active chat

---

quasar.conf.js

Supposedly, these workbox options will cause the service worker it
generates to automatically update the PWA. We will see...

Update workbox options to automatically update PWA

---

src/layouts/TopicLayout.vue

Topic drawer was automatically opening on mobile and quite annoying.
This should make it not do that, but still show up on desktop.

Don't automatically show drawer on small screens

---

src/components/topic/TopicMessage.vue
src/stores/topics.ts

Reactivity on voting and other message actions in topics was for
messages which had been loaded prior to the last time the app had been
loaded. This was because the individual topic message lists were not
shared with the messageIndex. It is important that these objects are the
same otherwise both will need to be updated in order to trigger
reactivity. This commit changes the saved state to only store
payloadDigests for the topics, and then rehydrates them from the same
objects as the messageIndex.

Ensure rehydrating topic messages share object w/ messageIndex

---

src/stores/topics.ts

If the user had the old format for saving topic data, blow it out.

Wipe out legacy topic serialization

---

src/stores/topics.ts

The previous commit to fix topics left out the messageIndex restoration,
which led to topics loading as blank after a second refresh. Ensure
messageIndex is properly restored.

Fix restoration of messageIndex

---

src/utils/constants.ts

This is using quite a bit of bandwidth because people are uploading
large avatar pictures (and gifs). We need a way to ensure people don't
do this in the future. However, for now just update less as leaving
stamp open uses a ton of bandwidth over time.

Increase default profile update interval to 1 hour

---

src/components/topic/TopicMessage.vue
src/pages/Topic.vue

Currently, due to a bug, if there is a message posted to a subtopic of
something subscribed to, and you vote for it, it will only vote 1 XPI
and also subscribe to the topic. This commit fixes it so that the
software does not add the new topic.

Don't add subtopics when voting

---

src/App.vue
src/components/panels/ForumDrawer.vue
src/components/panels/LeftDrawer.vue
src/layouts/MainLayout.vue

Currently, most of the setup and loading code is on the MainLayout which
causes problems as the MainLayout needs to support *every* subroute. The
result of this is that QPages need to be nexted in weird ways across
chats, topics, etc. in order to support footers and headers properly.
By moving the setup code to App.vue this will allow for not having to
use MainLayout as the layout for all pages and allow a cleaner setup
between topics and chats.

Move most of the setup code to App.vue

---

src/App.vue
src/boot/setup-apis.ts
src/utils/clients.ts

A lot of components require use of a mix of the composition and class
APIs in vue due to not having a way to get at the wallet without `this`.
Thus, they cannot be used from `setup()` functions. This commit adds a
singleton for these two objects so they can be used from within the
composition API.

Add `useWallet` and `useRelayClient` for composition API

---

src/components/chat/messages/ChatMessage.vue
src/components/chat/messages/ChatMessageSuffixButtons.vue

Ensure chat bubbles have a width enough to show menu items, so it
doesn't bounce around in size. Also, always show menu expansion option
even on desktop.

Change how chat bubbles are shown/hidden

---

src/cashweb/types/messages.ts
src/pages/Chat.vue

Add `payloadDigest` to the `Message` type to avoid typeerrors in
Chat.vue, also fix a null/undefined check

Fix type issues in Chat.vue

---

src/App.vue

Automatic local topics were not replacing multiple spaces with dashes.
This changes it to a global replace.

Ensure all spaces are replaced by dashes in topic names

---

src/components/chat/messages/ChatMessage.vue
src/pages/Chat.vue

Updating quasar seems to have changes the refs element to return an
array of possible elements. This commit deletes some old dead code, as
well as fix the behavior to obtain the correct ref for the message div.

Fix scrolling to replies

---

src/components/chat/ChatList.vue
src/components/panels/LeftDrawer.vue
src/components/topic/TopicList.vue
src/components/topic/TopicListLink.vue

Topics could end up having the impact of occluding DMs. This commit reorganizes the left drawer to have a specific topic tab. Also, add in a badge to the DM view so that it's clear if a message is waiting for you there. Finally, It also cleans up the LeftDrawer a bit as there was a bunch of unused code in the setup.

Move topics to their own tab on the left drawer

---

src/pages/Send.vue

Missing param for the vue template was causing it to be unable to send lotus anymore.
Closes #633

Fix Send Lotus dialog

---

src/cashweb/relay/index.ts
src/components/dialogs/TransactionDialog.vue
src/pages/Send.vue
src/utils/notifications.ts

There was an view action on the notification from the send page which did not do anything. 
Also, the transaction dialogs did not contain links to our explorer. This commit adds both.
Closes  #624

Update Send page to actually provide a link to the sent transaction

---

src/components/chat/ChatInput.vue
src/components/panels/ContactCard.vue
src/pages/Chat.vue
src/stores/chats.ts
src/utils/constants.ts

This input box was automatically changing the input and losing the input location of where users were typing. This commit should fix that behavior by not reformating the value on every keypress.
Closes #621

Fix crazy behavior on the stamp amount input box

---

src/cashweb/keyserver/index.ts
src/cashweb/wallet/index.ts
src/pages/Setup.vue

The constructTransaction function was not properly ignoring frozen UTXOs leading to the relay signup failing after the user's metadata had been sent to the metadata server. This was due to it trying to use the same UTXO over again for relay signup (which had just been spent). Additionally, when posting metadata any failures were being consumed leading to it improperly reporting errors.

Fix signup issue when having only one UTXO available

---

src/utils/constants.ts

Was causing problems as the default was mistakenly lower than the minimum (and also dust).

Fix default stamp amount to be 1XPI

---

src/cashweb/wallet/index.ts
src/cashweb/wallet/storage/level-storage.ts

The deleted UTXO cache was being updated when the wallet was reset this was causing UTXOs not to be re-added when they were scanned again later. So, even though the balances were updated in the Pinia wallet store, the UTXOs would not be available for use when trying to send another transaction.

[bug] Fix clearing of UTXOs when resetting key on setup

---

.github/workflows/workflow.yml

Node version is out of date for expected version.

[gh-actions] Fix github lint workflows

---

src/utils/constants.ts

I removed this bot along time ago, remove the default contact so that people don't send messages into the void for now.

[contacts] Remove default contact that was dead

---

src/stores/topics.ts

Get rid of the crypto group in favor of a trading group, and add a help topic.

[topics] Update default topics

---

src/cashweb/wallet/storage/level-storage.ts

We attempt to clean up state all over the place excessively. This leads sometimes to attempting to delete a UTXO twice and failing to actually clean out the cache. This leads to messages potentially failing to send repeatedly when a UTXO gets "stuck" in this way.

[fix] Capture error on deleting already deleted key

---

src/components/dialogs/TransactionDialog.vue

As per title. Was generating console errors for no good reason.

[fix] Remove unused (required) txid prop from TransactionDialog

---

src/components/dialogs/SeedPhraseDialog.vue
src/components/panels/SettingsPanel.vue
src/i18n/en-us/index.ts
src/i18n/fr-fr/index.ts
src/pages/Receive.vue

Based on user complaints, the seed phrase now shows on the main settings drawer rather than the receive screen. People didn't see the justification for putting it there -- and honestly, it only makes sense to an engineer.

[ui] Move seed phrase display to settings drawer

---

src/components/dialogs/ImageDialog.vue
src/components/dialogs/SeedPhraseDialog.vue
src/components/dialogs/TransactionDialog.vue
src/i18n/en-us/index.ts
src/i18n/fr-fr/index.ts
src/pages/Receive.vue

We don't need the word "Close" specialized for each different dialog box. It's also not setup correctly for english everywhere. This commit should fix that.

[i18n] Generalize close string

---

src/cashweb/relay/index.ts

Fix a bug where a message send error would enter an infite retry loop causing endless transactions to be spammed incorrectly if the 50tx chain limit was hit... Which is bad.

[fix] Ensure message send errors don't spam

---

src/boot/setup-apis.ts

Sometimes loading the local storage takes longer that loading remote storage. When the local storage finally loads, it wipes out the remote messages which were loaded causing issues. This commit temporarily awaits loading all the local storage before remote messages.
In the future it would be better to do both async and ensure the stores are merged.

Ensure chat store is fully restored before loading new messages

---

src/components/SubscribeDialog.vue

When first loading Stamp, the links are now incorrect. This makes it difficult for people just trying stamp to find the patreon and the givelotus chat so they can get some XPI.

Fix links in the subscription dialog

---

.vscode/settings.json

Formatting settings were out of date with the latest version of VS Code causing it not to correctly format on save.

fix(vscode): fix in-repo vs code settings
